package oracle.apps.po.rscapps.oss.iftransactions.common.entityobjects;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import oracle.apps.fnd.framework.server.OADBTransaction;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class RscIfbTransactionsBatchEOImpl extends OAEntityImpl 
{
  protected static final int BATCHID = 0;
  protected static final int CUSTINFONAME = 1;
  protected static final int CUSTINFOADDRESS1 = 2;
  protected static final int CUSTINFOADDRESS2 = 3;
  protected static final int CUSTINFOADDRESS3 = 4;
  protected static final int CUSTINFOCITY = 5;
  protected static final int CUSTINFOSTATE = 6;
  protected static final int CUSTINFOZIP = 7;
  protected static final int CUSTINFOPHONE = 8;
  protected static final int CUSTINFOFAX = 9;
  protected static final int CUSTINFOEMAIL = 10;
  protected static final int PURCHASEDATE = 11;
  protected static final int PURCHASEPLACE = 12;
  protected static final int PURCHASEUPGRADEREASON = 13;
  protected static final int PURCHASEUPGRADESOURCE = 14;
  protected static final int DEALERNAME = 15;
  protected static final int DEALERID = 16;
  protected static final int DEALERSIGNATURE = 17;
  protected static final int CLAIMSUBMISSIONDATE = 18;
  protected static final int DISTRIBUTORNAME = 19;
  protected static final int DISTRIBUTORID = 20;
  protected static final int ADDITIONALINFO1 = 21;
  protected static final int ADDITIONALINFO2 = 22;
  protected static final int ADDITIONALINFO3 = 23;
  protected static final int ADDITIONALINFO4 = 24;
  protected static final int ADDITIONALINFO5 = 25;
  protected static final int ADDITIONALINFO6 = 26;
  protected static final int ADDITIONALINFO7 = 27;
  protected static final int ADDITIONALINFO8 = 28;
  protected static final int ADDITIONALINFO9 = 29;
  protected static final int ADDITIONALINFO10 = 30;
  protected static final int ADDITIONALINFO11 = 31;
  protected static final int ADDITIONALINFO12 = 32;
  protected static final int ADDITIONALINFO13 = 33;
  protected static final int ADDITIONALINFO14 = 34;
  protected static final int ADDITIONALINFO15 = 35;
  protected static final int WFKEY = 36;
  protected static final int WFITEMTYPE = 37;
  protected static final int WFITEMKEY = 38;
  protected static final int WFUSERKEY = 39;
  protected static final int WFAPPROVER = 40;
  protected static final int WFPERFORMER = 41;
  protected static final int WFOWNER = 42;
  protected static final int WFINITIATEDBY = 43;
  protected static final int APPROVALNEEDEDFROM = 44;
  protected static final int STATUS = 45;
  protected static final int CREATEDBY = 46;
  protected static final int LASTUPDATELOGIN = 47;
  protected static final int LASTUPDATEDBY = 48;
  protected static final int CREATIONDATE = 49;
  protected static final int LASTUPDATEDATE = 50;
  protected static final int BATTERYPLAN = 51;
  protected static final int CUSTOMERREQUESTEDREFUND = 52;
  protected static final int REFUNDDATE = 53;
  protected static final int REFUNDAMOUNT = 54;
  protected static final int RECOVERYEFFORTS = 55;
  protected static final int LPUSED = 56;
  protected static final int LPTYPE = 57;
  protected static final int BREED1 = 58;
  protected static final int AGE1 = 59;
  protected static final int SEX1 = 60;
  protected static final int SPAYNEUTER1 = 61;
  protected static final int BREED2 = 62;
  protected static final int AGE2 = 63;
  protected static final int SEX2 = 64;
  protected static final int SPAYNEUTER2 = 65;
  protected static final int BREED3 = 66;
  protected static final int AGE3 = 67;
  protected static final int SEX3 = 68;
  protected static final int SPAYNEUTER3 = 69;
  protected static final int VETLOCATOR = 70;
  protected static final int VETPETSAFEPRODUCTS = 71;
  protected static final int APPROVALNEEDEDFROMSTR = 72;









  private static oracle.apps.fnd.framework.server.OAEntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public RscIfbTransactionsBatchEOImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (oracle.apps.fnd.framework.server.OAEntityDefImpl)EntityDefImpl.findDefObject("oracle.apps.po.rscapps.oss.iftransactions.common.entityobjects.RscIfbTransactionsBatchEO");
    }
    return mDefinitionObject;
  }









  /**
   * 
   * Add attribute defaulting logic in this method.
   */
  public void create(AttributeList attributeList)
  {
    super.create(attributeList);

    // Default BATCH_ID value to sequence generated value
    OADBTransaction oadb = getOADBTransaction();
    Number batchId = oadb.getSequenceValue("RSC_IFB_UPGRADES_BATCH_SEQ");
    setBatchId(batchId);

    Date currDate=(Date)oadb.getCurrentDBDate();
    setClaimSubmissionDate(currDate);
    if (getRefundDate() == null)
    {
      setRefundDate(currDate);
    }
    if (getCustomerRequestedRefund() == null)
    {
      setCustomerRequestedRefund(currDate);
    }

    String dealerName = "";
    PreparedStatement	pstmtDealerName = null ;
    ResultSet rsetDealerName = null;


    String distributorName = "";
    PreparedStatement	pstmtDistributorName = null ;
    ResultSet rsetDistributorName = null;

    int approvalNeedFrom = 0;
    PreparedStatement	pstmtApprovalNeedFrom = null ;
    ResultSet rsetApprovalNeedFrom = null;

    String approvalNeedFromStr = "";
    PreparedStatement	pstmtApprovalNeedFromStr = null ;
    ResultSet rsetApprovalNeedFromStr = null;
    
    String userNameTemp = oadb.getUserName();
    
    try {    
      pstmtDealerName = oadb.createPreparedStatement("SELECT RSC_IFB_OSS_UPGRADES_PKG.GET_DEALER_NAME(:1) FROM DUAL",  1);
      pstmtDealerName.setString(1, userNameTemp);
      rsetDealerName = pstmtDealerName.executeQuery();    
      if(rsetDealerName!=null) 
      {
        if(rsetDealerName.next())
          dealerName = rsetDealerName.getString(1);          
      }

      pstmtDistributorName = oadb.createPreparedStatement("SELECT RSC_IFB_OSS_UPGRADES_PKG.GET_DISTRIBUTOR_NAME(:1) FROM DUAL",  1);
      pstmtDistributorName.setString(1, userNameTemp);
      rsetDistributorName = pstmtDistributorName.executeQuery();    
      if(rsetDistributorName!=null) 
      {
        if(rsetDistributorName.next())
          distributorName = rsetDistributorName.getString(1);          
      }      
     
      pstmtApprovalNeedFrom = oadb.createPreparedStatement("SELECT RSC_IFB_OSS_UPGRADES_PKG.GET_MY_APPROVER_PARTY_ID(:1) FROM DUAL",  1);
      pstmtApprovalNeedFrom.setString(1, userNameTemp);
      rsetApprovalNeedFrom = pstmtApprovalNeedFrom.executeQuery();    
      if(rsetApprovalNeedFrom!=null) 
      {
        if(rsetApprovalNeedFrom.next()) 
        {
          approvalNeedFrom = rsetApprovalNeedFrom.getInt(1);
        }
      }

      pstmtApprovalNeedFromStr = oadb.createPreparedStatement("SELECT RSC_IFB_OSS_UPGRADES_PKG.GET_MY_APPROVER_PARTY_NAME(:1) FROM DUAL",  1);
      pstmtApprovalNeedFromStr.setString(1, userNameTemp);
      rsetApprovalNeedFromStr = pstmtApprovalNeedFromStr.executeQuery();    
      if(rsetApprovalNeedFromStr!=null) 
      {
        if(rsetApprovalNeedFromStr.next()) 
        {
          approvalNeedFromStr = rsetApprovalNeedFromStr.getString(1);          
        }
      }      
      
    } catch(Exception err) {
        err.printStackTrace();
    }

//    System.out.println("userNameTemp ---> " + userNameTemp);
//    System.out.println("dealerName ---> " + dealerName);
//    System.out.println("approvalNeedFrom ---> " + approvalNeedFrom);
//    System.out.println("approvalNeedFromStr ---> " + approvalNeedFromStr);    
    
    setDealerName(dealerName);
    setDistributorName(distributorName);
    
    setStatus("PENDING_APPROVAL");  
    setApprovalNeededFrom(new Number(approvalNeedFrom));
    setApprovalNeededFromStr(approvalNeedFromStr);
  }

  /**
   * 
   * Add entity remove logic in this method.
   */
  public void remove()
  {
    super.remove();
  }

  /**
   * 
   * Add Entity validation code in this method.
   */
  protected void validateEntity()
  {
    super.validateEntity();
  }

  /**
   * 
   * Add locking logic here.
   */
  public void lock()
  {
    super.lock();
  }

  /**
   * 
   * Custom DML update/insert/delete logic here.
   */
  protected void doDML(int operation, TransactionEvent e)
  {
    super.doDML(operation, e);
  }

  /**
   * 
   * Gets the attribute value for BatchId, using the alias name BatchId
   */
  public Number getBatchId()
  {
    return (Number)getAttributeInternal(BATCHID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for BatchId
   */
  public void setBatchId(Number value)
  {
    setAttributeInternal(BATCHID, value);
  }

  /**
   * 
   * Gets the attribute value for CustInfoName, using the alias name CustInfoName
   */
  public String getCustInfoName()
  {
    return (String)getAttributeInternal(CUSTINFONAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CustInfoName
   */
  public void setCustInfoName(String value)
  {
    setAttributeInternal(CUSTINFONAME, value);
  }

  /**
   * 
   * Gets the attribute value for CustInfoAddress1, using the alias name CustInfoAddress1
   */
  public String getCustInfoAddress1()
  {
    return (String)getAttributeInternal(CUSTINFOADDRESS1);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CustInfoAddress1
   */
  public void setCustInfoAddress1(String value)
  {
    setAttributeInternal(CUSTINFOADDRESS1, value);
  }

  /**
   * 
   * Gets the attribute value for CustInfoAddress2, using the alias name CustInfoAddress2
   */
  public String getCustInfoAddress2()
  {
    return (String)getAttributeInternal(CUSTINFOADDRESS2);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CustInfoAddress2
   */
  public void setCustInfoAddress2(String value)
  {
    setAttributeInternal(CUSTINFOADDRESS2, value);
  }

  /**
   * 
   * Gets the attribute value for CustInfoAddress3, using the alias name CustInfoAddress3
   */
  public String getCustInfoAddress3()
  {
    return (String)getAttributeInternal(CUSTINFOADDRESS3);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CustInfoAddress3
   */
  public void setCustInfoAddress3(String value)
  {
    setAttributeInternal(CUSTINFOADDRESS3, value);
  }

  /**
   * 
   * Gets the attribute value for CustInfoCity, using the alias name CustInfoCity
   */
  public String getCustInfoCity()
  {
    return (String)getAttributeInternal(CUSTINFOCITY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CustInfoCity
   */
  public void setCustInfoCity(String value)
  {
    setAttributeInternal(CUSTINFOCITY, value);
  }

  /**
   * 
   * Gets the attribute value for CustInfoState, using the alias name CustInfoState
   */
  public String getCustInfoState()
  {
    return (String)getAttributeInternal(CUSTINFOSTATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CustInfoState
   */
  public void setCustInfoState(String value)
  {
    setAttributeInternal(CUSTINFOSTATE, value);
  }

  /**
   * 
   * Gets the attribute value for CustInfoZip, using the alias name CustInfoZip
   */
  public Number getCustInfoZip()
  {
    return (Number)getAttributeInternal(CUSTINFOZIP);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CustInfoZip
   */
  public void setCustInfoZip(Number value)
  {
    setAttributeInternal(CUSTINFOZIP, value);
  }

  /**
   * 
   * Gets the attribute value for CustInfoPhone, using the alias name CustInfoPhone
   */
  public Number getCustInfoPhone()
  {
    return (Number)getAttributeInternal(CUSTINFOPHONE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CustInfoPhone
   */
  public void setCustInfoPhone(Number value)
  {
    setAttributeInternal(CUSTINFOPHONE, value);
  }

  /**
   * 
   * Gets the attribute value for CustInfoFax, using the alias name CustInfoFax
   */
  public Number getCustInfoFax()
  {
    return (Number)getAttributeInternal(CUSTINFOFAX);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CustInfoFax
   */
  public void setCustInfoFax(Number value)
  {
    setAttributeInternal(CUSTINFOFAX, value);
  }

  /**
   * 
   * Gets the attribute value for CustInfoEmail, using the alias name CustInfoEmail
   */
  public String getCustInfoEmail()
  {
    return (String)getAttributeInternal(CUSTINFOEMAIL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CustInfoEmail
   */
  public void setCustInfoEmail(String value)
  {
    setAttributeInternal(CUSTINFOEMAIL, value);
  }

  /**
   * 
   * Gets the attribute value for PurchaseDate, using the alias name PurchaseDate
   */
  public Date getPurchaseDate()
  {
    return (Date)getAttributeInternal(PURCHASEDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PurchaseDate
   */
  public void setPurchaseDate(Date value)
  {
    setAttributeInternal(PURCHASEDATE, value);
  }

  /**
   * 
   * Gets the attribute value for PurchasePlace, using the alias name PurchasePlace
   */
  public String getPurchasePlace()
  {
    return (String)getAttributeInternal(PURCHASEPLACE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PurchasePlace
   */
  public void setPurchasePlace(String value)
  {
    setAttributeInternal(PURCHASEPLACE, value);
  }

  /**
   * 
   * Gets the attribute value for PurchaseUpgradeReason, using the alias name PurchaseUpgradeReason
   */
  public String getPurchaseUpgradeReason()
  {
    return (String)getAttributeInternal(PURCHASEUPGRADEREASON);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PurchaseUpgradeReason
   */
  public void setPurchaseUpgradeReason(String value)
  {
    setAttributeInternal(PURCHASEUPGRADEREASON, value);
  }

  /**
   * 
   * Gets the attribute value for PurchaseUpgradeSource, using the alias name PurchaseUpgradeSource
   */
  public String getPurchaseUpgradeSource()
  {
    return (String)getAttributeInternal(PURCHASEUPGRADESOURCE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PurchaseUpgradeSource
   */
  public void setPurchaseUpgradeSource(String value)
  {
    setAttributeInternal(PURCHASEUPGRADESOURCE, value);
  }

  /**
   * 
   * Gets the attribute value for DealerName, using the alias name DealerName
   */
  public String getDealerName()
  {
    return (String)getAttributeInternal(DEALERNAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DealerName
   */
  public void setDealerName(String value)
  {
    setAttributeInternal(DEALERNAME, value);
  }

  /**
   * 
   * Gets the attribute value for DealerId, using the alias name DealerId
   */
  public Number getDealerId()
  {
    return (Number)getAttributeInternal(DEALERID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DealerId
   */
  public void setDealerId(Number value)
  {
    setAttributeInternal(DEALERID, value);
  }

  /**
   * 
   * Gets the attribute value for DealerSignature, using the alias name DealerSignature
   */
  public String getDealerSignature()
  {
    return (String)getAttributeInternal(DEALERSIGNATURE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DealerSignature
   */
  public void setDealerSignature(String value)
  {
    setAttributeInternal(DEALERSIGNATURE, value);
  }

  /**
   * 
   * Gets the attribute value for ClaimSubmissionDate, using the alias name ClaimSubmissionDate
   */
  public Date getClaimSubmissionDate()
  {
    return (Date)getAttributeInternal(CLAIMSUBMISSIONDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ClaimSubmissionDate
   */
  public void setClaimSubmissionDate(Date value)
  {
    setAttributeInternal(CLAIMSUBMISSIONDATE, value);
  }

  /**
   * 
   * Gets the attribute value for DistributorName, using the alias name DistributorName
   */
  public String getDistributorName()
  {
    return (String)getAttributeInternal(DISTRIBUTORNAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DistributorName
   */
  public void setDistributorName(String value)
  {
    setAttributeInternal(DISTRIBUTORNAME, value);
  }

  /**
   * 
   * Gets the attribute value for DistributorId, using the alias name DistributorId
   */
  public Number getDistributorId()
  {
    return (Number)getAttributeInternal(DISTRIBUTORID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DistributorId
   */
  public void setDistributorId(Number value)
  {
    setAttributeInternal(DISTRIBUTORID, value);
  }

  /**
   * 
   * Gets the attribute value for AdditionalInfo1, using the alias name AdditionalInfo1
   */
  public String getAdditionalInfo1()
  {
    return (String)getAttributeInternal(ADDITIONALINFO1);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AdditionalInfo1
   */
  public void setAdditionalInfo1(String value)
  {
    setAttributeInternal(ADDITIONALINFO1, value);
  }

  /**
   * 
   * Gets the attribute value for AdditionalInfo2, using the alias name AdditionalInfo2
   */
  public String getAdditionalInfo2()
  {
    return (String)getAttributeInternal(ADDITIONALINFO2);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AdditionalInfo2
   */
  public void setAdditionalInfo2(String value)
  {
    setAttributeInternal(ADDITIONALINFO2, value);
  }

  /**
   * 
   * Gets the attribute value for AdditionalInfo3, using the alias name AdditionalInfo3
   */
  public String getAdditionalInfo3()
  {
    return (String)getAttributeInternal(ADDITIONALINFO3);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AdditionalInfo3
   */
  public void setAdditionalInfo3(String value)
  {
    setAttributeInternal(ADDITIONALINFO3, value);
  }

  /**
   * 
   * Gets the attribute value for AdditionalInfo4, using the alias name AdditionalInfo4
   */
  public String getAdditionalInfo4()
  {
    return (String)getAttributeInternal(ADDITIONALINFO4);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AdditionalInfo4
   */
  public void setAdditionalInfo4(String value)
  {
    setAttributeInternal(ADDITIONALINFO4, value);
  }

  /**
   * 
   * Gets the attribute value for AdditionalInfo5, using the alias name AdditionalInfo5
   */
  public String getAdditionalInfo5()
  {
    return (String)getAttributeInternal(ADDITIONALINFO5);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AdditionalInfo5
   */
  public void setAdditionalInfo5(String value)
  {
    setAttributeInternal(ADDITIONALINFO5, value);
  }

  /**
   * 
   * Gets the attribute value for AdditionalInfo6, using the alias name AdditionalInfo6
   */
  public String getAdditionalInfo6()
  {
    return (String)getAttributeInternal(ADDITIONALINFO6);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AdditionalInfo6
   */
  public void setAdditionalInfo6(String value)
  {
    setAttributeInternal(ADDITIONALINFO6, value);
  }

  /**
   * 
   * Gets the attribute value for AdditionalInfo7, using the alias name AdditionalInfo7
   */
  public String getAdditionalInfo7()
  {
    return (String)getAttributeInternal(ADDITIONALINFO7);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AdditionalInfo7
   */
  public void setAdditionalInfo7(String value)
  {
    setAttributeInternal(ADDITIONALINFO7, value);
  }

  /**
   * 
   * Gets the attribute value for AdditionalInfo8, using the alias name AdditionalInfo8
   */
  public String getAdditionalInfo8()
  {
    return (String)getAttributeInternal(ADDITIONALINFO8);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AdditionalInfo8
   */
  public void setAdditionalInfo8(String value)
  {
    setAttributeInternal(ADDITIONALINFO8, value);
  }

  /**
   * 
   * Gets the attribute value for AdditionalInfo9, using the alias name AdditionalInfo9
   */
  public String getAdditionalInfo9()
  {
    return (String)getAttributeInternal(ADDITIONALINFO9);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AdditionalInfo9
   */
  public void setAdditionalInfo9(String value)
  {
    setAttributeInternal(ADDITIONALINFO9, value);
  }

  /**
   * 
   * Gets the attribute value for AdditionalInfo10, using the alias name AdditionalInfo10
   */
  public String getAdditionalInfo10()
  {
    return (String)getAttributeInternal(ADDITIONALINFO10);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AdditionalInfo10
   */
  public void setAdditionalInfo10(String value)
  {
    setAttributeInternal(ADDITIONALINFO10, value);
  }

  /**
   * 
   * Gets the attribute value for AdditionalInfo11, using the alias name AdditionalInfo11
   */
  public String getAdditionalInfo11()
  {
    return (String)getAttributeInternal(ADDITIONALINFO11);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AdditionalInfo11
   */
  public void setAdditionalInfo11(String value)
  {
    setAttributeInternal(ADDITIONALINFO11, value);
  }

  /**
   * 
   * Gets the attribute value for AdditionalInfo12, using the alias name AdditionalInfo12
   */
  public String getAdditionalInfo12()
  {
    return (String)getAttributeInternal(ADDITIONALINFO12);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AdditionalInfo12
   */
  public void setAdditionalInfo12(String value)
  {
    setAttributeInternal(ADDITIONALINFO12, value);
  }

  /**
   * 
   * Gets the attribute value for AdditionalInfo13, using the alias name AdditionalInfo13
   */
  public String getAdditionalInfo13()
  {
    return (String)getAttributeInternal(ADDITIONALINFO13);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AdditionalInfo13
   */
  public void setAdditionalInfo13(String value)
  {
    setAttributeInternal(ADDITIONALINFO13, value);
  }

  /**
   * 
   * Gets the attribute value for AdditionalInfo14, using the alias name AdditionalInfo14
   */
  public String getAdditionalInfo14()
  {
    return (String)getAttributeInternal(ADDITIONALINFO14);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AdditionalInfo14
   */
  public void setAdditionalInfo14(String value)
  {
    setAttributeInternal(ADDITIONALINFO14, value);
  }

  /**
   * 
   * Gets the attribute value for AdditionalInfo15, using the alias name AdditionalInfo15
   */
  public String getAdditionalInfo15()
  {
    return (String)getAttributeInternal(ADDITIONALINFO15);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AdditionalInfo15
   */
  public void setAdditionalInfo15(String value)
  {
    setAttributeInternal(ADDITIONALINFO15, value);
  }

  /**
   * 
   * Gets the attribute value for WfKey, using the alias name WfKey
   */
  public String getWfKey()
  {
    return (String)getAttributeInternal(WFKEY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for WfKey
   */
  public void setWfKey(String value)
  {
    setAttributeInternal(WFKEY, value);
  }

  /**
   * 
   * Gets the attribute value for WfItemType, using the alias name WfItemType
   */
  public String getWfItemType()
  {
    return (String)getAttributeInternal(WFITEMTYPE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for WfItemType
   */
  public void setWfItemType(String value)
  {
    setAttributeInternal(WFITEMTYPE, value);
  }

  /**
   * 
   * Gets the attribute value for WfItemKey, using the alias name WfItemKey
   */
  public String getWfItemKey()
  {
    return (String)getAttributeInternal(WFITEMKEY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for WfItemKey
   */
  public void setWfItemKey(String value)
  {
    setAttributeInternal(WFITEMKEY, value);
  }

  /**
   * 
   * Gets the attribute value for WfUserKey, using the alias name WfUserKey
   */
  public String getWfUserKey()
  {
    return (String)getAttributeInternal(WFUSERKEY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for WfUserKey
   */
  public void setWfUserKey(String value)
  {
    setAttributeInternal(WFUSERKEY, value);
  }

  /**
   * 
   * Gets the attribute value for WfApprover, using the alias name WfApprover
   */
  public String getWfApprover()
  {
    return (String)getAttributeInternal(WFAPPROVER);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for WfApprover
   */
  public void setWfApprover(String value)
  {
    setAttributeInternal(WFAPPROVER, value);
  }

  /**
   * 
   * Gets the attribute value for WfPerformer, using the alias name WfPerformer
   */
  public String getWfPerformer()
  {
    return (String)getAttributeInternal(WFPERFORMER);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for WfPerformer
   */
  public void setWfPerformer(String value)
  {
    setAttributeInternal(WFPERFORMER, value);
  }

  /**
   * 
   * Gets the attribute value for WfOwner, using the alias name WfOwner
   */
  public String getWfOwner()
  {
    return (String)getAttributeInternal(WFOWNER);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for WfOwner
   */
  public void setWfOwner(String value)
  {
    setAttributeInternal(WFOWNER, value);
  }

  /**
   * 
   * Gets the attribute value for WfInitiatedBy, using the alias name WfInitiatedBy
   */
  public String getWfInitiatedBy()
  {
    return (String)getAttributeInternal(WFINITIATEDBY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for WfInitiatedBy
   */
  public void setWfInitiatedBy(String value)
  {
    setAttributeInternal(WFINITIATEDBY, value);
  }

  /**
   * 
   * Gets the attribute value for ApprovalNeededFrom, using the alias name ApprovalNeededFrom
   */
  public Number getApprovalNeededFrom()
  {
    return (Number)getAttributeInternal(APPROVALNEEDEDFROM);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ApprovalNeededFrom
   */
  public void setApprovalNeededFrom(Number value)
  {
    setAttributeInternal(APPROVALNEEDEDFROM, value);
  }

  /**
   * 
   * Gets the attribute value for Status, using the alias name Status
   */
  public String getStatus()
  {
    return (String)getAttributeInternal(STATUS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Status
   */
  public void setStatus(String value)
  {
    setAttributeInternal(STATUS, value);
  }

  /**
   * 
   * Gets the attribute value for CreatedBy, using the alias name CreatedBy
   */
  public Number getCreatedBy()
  {
    return (Number)getAttributeInternal(CREATEDBY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CreatedBy
   */
  public void setCreatedBy(Number value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * 
   * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
   */
  public Number getLastUpdateLogin()
  {
    return (Number)getAttributeInternal(LASTUPDATELOGIN);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LastUpdateLogin
   */
  public void setLastUpdateLogin(Number value)
  {
    setAttributeInternal(LASTUPDATELOGIN, value);
  }

  /**
   * 
   * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
   */
  public Number getLastUpdatedBy()
  {
    return (Number)getAttributeInternal(LASTUPDATEDBY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LastUpdatedBy
   */
  public void setLastUpdatedBy(Number value)
  {
    setAttributeInternal(LASTUPDATEDBY, value);
  }

  /**
   * 
   * Gets the attribute value for CreationDate, using the alias name CreationDate
   */
  public Date getCreationDate()
  {
    return (Date)getAttributeInternal(CREATIONDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CreationDate
   */
  public void setCreationDate(Date value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * 
   * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
   */
  public Date getLastUpdateDate()
  {
    return (Date)getAttributeInternal(LASTUPDATEDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LastUpdateDate
   */
  public void setLastUpdateDate(Date value)
  {
    setAttributeInternal(LASTUPDATEDATE, value);
  }


  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case BATCHID:
        return getBatchId();
      case CUSTINFONAME:
        return getCustInfoName();
      case CUSTINFOADDRESS1:
        return getCustInfoAddress1();
      case CUSTINFOADDRESS2:
        return getCustInfoAddress2();
      case CUSTINFOADDRESS3:
        return getCustInfoAddress3();
      case CUSTINFOCITY:
        return getCustInfoCity();
      case CUSTINFOSTATE:
        return getCustInfoState();
      case CUSTINFOZIP:
        return getCustInfoZip();
      case CUSTINFOPHONE:
        return getCustInfoPhone();
      case CUSTINFOFAX:
        return getCustInfoFax();
      case CUSTINFOEMAIL:
        return getCustInfoEmail();
      case PURCHASEDATE:
        return getPurchaseDate();
      case PURCHASEPLACE:
        return getPurchasePlace();
      case PURCHASEUPGRADEREASON:
        return getPurchaseUpgradeReason();
      case PURCHASEUPGRADESOURCE:
        return getPurchaseUpgradeSource();
      case DEALERNAME:
        return getDealerName();
      case DEALERID:
        return getDealerId();
      case DEALERSIGNATURE:
        return getDealerSignature();
      case CLAIMSUBMISSIONDATE:
        return getClaimSubmissionDate();
      case DISTRIBUTORNAME:
        return getDistributorName();
      case DISTRIBUTORID:
        return getDistributorId();
      case ADDITIONALINFO1:
        return getAdditionalInfo1();
      case ADDITIONALINFO2:
        return getAdditionalInfo2();
      case ADDITIONALINFO3:
        return getAdditionalInfo3();
      case ADDITIONALINFO4:
        return getAdditionalInfo4();
      case ADDITIONALINFO5:
        return getAdditionalInfo5();
      case ADDITIONALINFO6:
        return getAdditionalInfo6();
      case ADDITIONALINFO7:
        return getAdditionalInfo7();
      case ADDITIONALINFO8:
        return getAdditionalInfo8();
      case ADDITIONALINFO9:
        return getAdditionalInfo9();
      case ADDITIONALINFO10:
        return getAdditionalInfo10();
      case ADDITIONALINFO11:
        return getAdditionalInfo11();
      case ADDITIONALINFO12:
        return getAdditionalInfo12();
      case ADDITIONALINFO13:
        return getAdditionalInfo13();
      case ADDITIONALINFO14:
        return getAdditionalInfo14();
      case ADDITIONALINFO15:
        return getAdditionalInfo15();
      case WFKEY:
        return getWfKey();
      case WFITEMTYPE:
        return getWfItemType();
      case WFITEMKEY:
        return getWfItemKey();
      case WFUSERKEY:
        return getWfUserKey();
      case WFAPPROVER:
        return getWfApprover();
      case WFPERFORMER:
        return getWfPerformer();
      case WFOWNER:
        return getWfOwner();
      case WFINITIATEDBY:
        return getWfInitiatedBy();
      case APPROVALNEEDEDFROM:
        return getApprovalNeededFrom();
      case STATUS:
        return getStatus();
      case CREATEDBY:
        return getCreatedBy();
      case LASTUPDATELOGIN:
        return getLastUpdateLogin();
      case LASTUPDATEDBY:
        return getLastUpdatedBy();
      case CREATIONDATE:
        return getCreationDate();
      case LASTUPDATEDATE:
        return getLastUpdateDate();
      case BATTERYPLAN:
        return getBatteryPlan();
      case CUSTOMERREQUESTEDREFUND:
        return getCustomerRequestedRefund();
      case REFUNDDATE:
        return getRefundDate();
      case REFUNDAMOUNT:
        return getRefundAmount();
      case RECOVERYEFFORTS:
        return getRecoveryEfforts();
      case LPUSED:
        return getLpUsed();
      case LPTYPE:
        return getLpType();
      case BREED1:
        return getBreed1();
      case AGE1:
        return getAge1();
      case SEX1:
        return getSex1();
      case SPAYNEUTER1:
        return getSpayNeuter1();
      case BREED2:
        return getBreed2();
      case AGE2:
        return getAge2();
      case SEX2:
        return getSex2();
      case SPAYNEUTER2:
        return getSpayNeuter2();
      case BREED3:
        return getBreed3();
      case AGE3:
        return getAge3();
      case SEX3:
        return getSex3();
      case SPAYNEUTER3:
        return getSpayNeuter3();
      case VETLOCATOR:
        return getVetLocator();
      case VETPETSAFEPRODUCTS:
        return getVetPetsafeProducts();
      case APPROVALNEEDEDFROMSTR:
        return getApprovalNeededFromStr();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case BATCHID:
        setBatchId((Number)value);
        return;
      case CUSTINFONAME:
        setCustInfoName((String)value);
        return;
      case CUSTINFOADDRESS1:
        setCustInfoAddress1((String)value);
        return;
      case CUSTINFOADDRESS2:
        setCustInfoAddress2((String)value);
        return;
      case CUSTINFOADDRESS3:
        setCustInfoAddress3((String)value);
        return;
      case CUSTINFOCITY:
        setCustInfoCity((String)value);
        return;
      case CUSTINFOSTATE:
        setCustInfoState((String)value);
        return;
      case CUSTINFOZIP:
        setCustInfoZip((Number)value);
        return;
      case CUSTINFOPHONE:
        setCustInfoPhone((Number)value);
        return;
      case CUSTINFOFAX:
        setCustInfoFax((Number)value);
        return;
      case CUSTINFOEMAIL:
        setCustInfoEmail((String)value);
        return;
      case PURCHASEDATE:
        setPurchaseDate((Date)value);
        return;
      case PURCHASEPLACE:
        setPurchasePlace((String)value);
        return;
      case PURCHASEUPGRADEREASON:
        setPurchaseUpgradeReason((String)value);
        return;
      case PURCHASEUPGRADESOURCE:
        setPurchaseUpgradeSource((String)value);
        return;
      case DEALERNAME:
        setDealerName((String)value);
        return;
      case DEALERID:
        setDealerId((Number)value);
        return;
      case DEALERSIGNATURE:
        setDealerSignature((String)value);
        return;
      case CLAIMSUBMISSIONDATE:
        setClaimSubmissionDate((Date)value);
        return;
      case DISTRIBUTORNAME:
        setDistributorName((String)value);
        return;
      case DISTRIBUTORID:
        setDistributorId((Number)value);
        return;
      case ADDITIONALINFO1:
        setAdditionalInfo1((String)value);
        return;
      case ADDITIONALINFO2:
        setAdditionalInfo2((String)value);
        return;
      case ADDITIONALINFO3:
        setAdditionalInfo3((String)value);
        return;
      case ADDITIONALINFO4:
        setAdditionalInfo4((String)value);
        return;
      case ADDITIONALINFO5:
        setAdditionalInfo5((String)value);
        return;
      case ADDITIONALINFO6:
        setAdditionalInfo6((String)value);
        return;
      case ADDITIONALINFO7:
        setAdditionalInfo7((String)value);
        return;
      case ADDITIONALINFO8:
        setAdditionalInfo8((String)value);
        return;
      case ADDITIONALINFO9:
        setAdditionalInfo9((String)value);
        return;
      case ADDITIONALINFO10:
        setAdditionalInfo10((String)value);
        return;
      case ADDITIONALINFO11:
        setAdditionalInfo11((String)value);
        return;
      case ADDITIONALINFO12:
        setAdditionalInfo12((String)value);
        return;
      case ADDITIONALINFO13:
        setAdditionalInfo13((String)value);
        return;
      case ADDITIONALINFO14:
        setAdditionalInfo14((String)value);
        return;
      case ADDITIONALINFO15:
        setAdditionalInfo15((String)value);
        return;
      case WFKEY:
        setWfKey((String)value);
        return;
      case WFITEMTYPE:
        setWfItemType((String)value);
        return;
      case WFITEMKEY:
        setWfItemKey((String)value);
        return;
      case WFUSERKEY:
        setWfUserKey((String)value);
        return;
      case WFAPPROVER:
        setWfApprover((String)value);
        return;
      case WFPERFORMER:
        setWfPerformer((String)value);
        return;
      case WFOWNER:
        setWfOwner((String)value);
        return;
      case WFINITIATEDBY:
        setWfInitiatedBy((String)value);
        return;
      case APPROVALNEEDEDFROM:
        setApprovalNeededFrom((Number)value);
        return;
      case STATUS:
        setStatus((String)value);
        return;
      case CREATEDBY:
        setCreatedBy((Number)value);
        return;
      case LASTUPDATELOGIN:
        setLastUpdateLogin((Number)value);
        return;
      case LASTUPDATEDBY:
        setLastUpdatedBy((Number)value);
        return;
      case CREATIONDATE:
        setCreationDate((Date)value);
        return;
      case LASTUPDATEDATE:
        setLastUpdateDate((Date)value);
        return;
      case BATTERYPLAN:
        setBatteryPlan((Number)value);
        return;
      case CUSTOMERREQUESTEDREFUND:
        setCustomerRequestedRefund((Date)value);
        return;
      case REFUNDDATE:
        setRefundDate((Date)value);
        return;
      case REFUNDAMOUNT:
        setRefundAmount((Number)value);
        return;
      case RECOVERYEFFORTS:
        setRecoveryEfforts((String)value);
        return;
      case LPUSED:
        setLpUsed((Number)value);
        return;
      case LPTYPE:
        setLpType((String)value);
        return;
      case BREED1:
        setBreed1((Number)value);
        return;
      case AGE1:
        setAge1((Number)value);
        return;
      case SEX1:
        setSex1((Number)value);
        return;
      case SPAYNEUTER1:
        setSpayNeuter1((Number)value);
        return;
      case BREED2:
        setBreed2((Number)value);
        return;
      case AGE2:
        setAge2((Number)value);
        return;
      case SEX2:
        setSex2((Number)value);
        return;
      case SPAYNEUTER2:
        setSpayNeuter2((Number)value);
        return;
      case BREED3:
        setBreed3((Number)value);
        return;
      case AGE3:
        setAge3((Number)value);
        return;
      case SEX3:
        setSex3((Number)value);
        return;
      case SPAYNEUTER3:
        setSpayNeuter3((Number)value);
        return;
      case VETLOCATOR:
        setVetLocator((Number)value);
        return;
      case VETPETSAFEPRODUCTS:
        setVetPetsafeProducts((Number)value);
        return;
      case APPROVALNEEDEDFROMSTR:
        setApprovalNeededFromStr((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }








  /**
   * 
   * Gets the attribute value for ApprovalNeededFromStr, using the alias name ApprovalNeededFromStr
   */
  public String getApprovalNeededFromStr()
  {
    return (String)getAttributeInternal(APPROVALNEEDEDFROMSTR);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ApprovalNeededFromStr
   */
  public void setApprovalNeededFromStr(String value)
  {
    setAttributeInternal(APPROVALNEEDEDFROMSTR, value);
  }


  /**
   * 
   * Gets the attribute value for BatteryPlan, using the alias name BatteryPlan
   */
  public Number getBatteryPlan()
  {
    return (Number)getAttributeInternal(BATTERYPLAN);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for BatteryPlan
   */
  public void setBatteryPlan(Number value)
  {
    setAttributeInternal(BATTERYPLAN, value);
  }

  /**
   * 
   * Gets the attribute value for CustomerRequestedRefund, using the alias name CustomerRequestedRefund
   */
  public Date getCustomerRequestedRefund()
  {
    return (Date)getAttributeInternal(CUSTOMERREQUESTEDREFUND);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CustomerRequestedRefund
   */
  public void setCustomerRequestedRefund(Date value)
  {
    setAttributeInternal(CUSTOMERREQUESTEDREFUND, value);
  }

  /**
   * 
   * Gets the attribute value for RefundDate, using the alias name RefundDate
   */
  public Date getRefundDate()
  {
    return (Date)getAttributeInternal(REFUNDDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for RefundDate
   */
  public void setRefundDate(Date value)
  {
    setAttributeInternal(REFUNDDATE, value);
  }

  /**
   * 
   * Gets the attribute value for RefundAmount, using the alias name RefundAmount
   */
  public Number getRefundAmount()
  {
    return (Number)getAttributeInternal(REFUNDAMOUNT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for RefundAmount
   */
  public void setRefundAmount(Number value)
  {
    setAttributeInternal(REFUNDAMOUNT, value);
  }

  /**
   * 
   * Gets the attribute value for RecoveryEfforts, using the alias name RecoveryEfforts
   */
  public String getRecoveryEfforts()
  {
    return (String)getAttributeInternal(RECOVERYEFFORTS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for RecoveryEfforts
   */
  public void setRecoveryEfforts(String value)
  {
    setAttributeInternal(RECOVERYEFFORTS, value);
  }

  /**
   * 
   * Gets the attribute value for LpUsed, using the alias name LpUsed
   */
  public Number getLpUsed()
  {
    return (Number)getAttributeInternal(LPUSED);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LpUsed
   */
  public void setLpUsed(Number value)
  {
    setAttributeInternal(LPUSED, value);
  }

  /**
   * 
   * Gets the attribute value for LpType, using the alias name LpType
   */
  public String getLpType()
  {
    return (String)getAttributeInternal(LPTYPE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LpType
   */
  public void setLpType(String value)
  {
    setAttributeInternal(LPTYPE, value);
  }

  /**
   * 
   * Gets the attribute value for Breed1, using the alias name Breed1
   */
  public Number getBreed1()
  {
    return (Number)getAttributeInternal(BREED1);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Breed1
   */
  public void setBreed1(Number value)
  {
    setAttributeInternal(BREED1, value);
  }

  /**
   * 
   * Gets the attribute value for Age1, using the alias name Age1
   */
  public Number getAge1()
  {
    return (Number)getAttributeInternal(AGE1);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Age1
   */
  public void setAge1(Number value)
  {
    setAttributeInternal(AGE1, value);
  }

  /**
   * 
   * Gets the attribute value for Sex1, using the alias name Sex1
   */
  public Number getSex1()
  {
    return (Number)getAttributeInternal(SEX1);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Sex1
   */
  public void setSex1(Number value)
  {
    setAttributeInternal(SEX1, value);
  }

  /**
   * 
   * Gets the attribute value for SpayNeuter1, using the alias name SpayNeuter1
   */
  public Number getSpayNeuter1()
  {
    return (Number)getAttributeInternal(SPAYNEUTER1);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SpayNeuter1
   */
  public void setSpayNeuter1(Number value)
  {
    setAttributeInternal(SPAYNEUTER1, value);
  }

  /**
   * 
   * Gets the attribute value for Breed2, using the alias name Breed2
   */
  public Number getBreed2()
  {
    return (Number)getAttributeInternal(BREED2);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Breed2
   */
  public void setBreed2(Number value)
  {
    setAttributeInternal(BREED2, value);
  }

  /**
   * 
   * Gets the attribute value for Age2, using the alias name Age2
   */
  public Number getAge2()
  {
    return (Number)getAttributeInternal(AGE2);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Age2
   */
  public void setAge2(Number value)
  {
    setAttributeInternal(AGE2, value);
  }

  /**
   * 
   * Gets the attribute value for Sex2, using the alias name Sex2
   */
  public Number getSex2()
  {
    return (Number)getAttributeInternal(SEX2);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Sex2
   */
  public void setSex2(Number value)
  {
    setAttributeInternal(SEX2, value);
  }

  /**
   * 
   * Gets the attribute value for SpayNeuter2, using the alias name SpayNeuter2
   */
  public Number getSpayNeuter2()
  {
    return (Number)getAttributeInternal(SPAYNEUTER2);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SpayNeuter2
   */
  public void setSpayNeuter2(Number value)
  {
    setAttributeInternal(SPAYNEUTER2, value);
  }

  /**
   * 
   * Gets the attribute value for Breed3, using the alias name Breed3
   */
  public Number getBreed3()
  {
    return (Number)getAttributeInternal(BREED3);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Breed3
   */
  public void setBreed3(Number value)
  {
    setAttributeInternal(BREED3, value);
  }

  /**
   * 
   * Gets the attribute value for Age3, using the alias name Age3
   */
  public Number getAge3()
  {
    return (Number)getAttributeInternal(AGE3);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Age3
   */
  public void setAge3(Number value)
  {
    setAttributeInternal(AGE3, value);
  }

  /**
   * 
   * Gets the attribute value for Sex3, using the alias name Sex3
   */
  public Number getSex3()
  {
    return (Number)getAttributeInternal(SEX3);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Sex3
   */
  public void setSex3(Number value)
  {
    setAttributeInternal(SEX3, value);
  }

  /**
   * 
   * Gets the attribute value for SpayNeuter3, using the alias name SpayNeuter3
   */
  public Number getSpayNeuter3()
  {
    return (Number)getAttributeInternal(SPAYNEUTER3);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SpayNeuter3
   */
  public void setSpayNeuter3(Number value)
  {
    setAttributeInternal(SPAYNEUTER3, value);
  }

  /**
   * 
   * Gets the attribute value for VetLocator, using the alias name VetLocator
   */
  public Number getVetLocator()
  {
    return (Number)getAttributeInternal(VETLOCATOR);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for VetLocator
   */
  public void setVetLocator(Number value)
  {
    setAttributeInternal(VETLOCATOR, value);
  }

  /**
   * 
   * Gets the attribute value for VetPetsafeProducts, using the alias name VetPetsafeProducts
   */
  public Number getVetPetsafeProducts()
  {
    return (Number)getAttributeInternal(VETPETSAFEPRODUCTS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for VetPetsafeProducts
   */
  public void setVetPetsafeProducts(Number value)
  {
    setAttributeInternal(VETPETSAFEPRODUCTS, value);
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number batchId)
  {
    return new Key(new Object[] {batchId});
  }























}