package oracle.apps.po.rscapps.oss.iftransactions.common.entityobjects;
import oracle.apps.fnd.framework.server.OAEntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.AttributeList;
import oracle.jbo.server.TransactionEvent;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
import oracle.jbo.Key;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class RscIfbTransactionsPricingInfoEOImpl extends OAEntityImpl 
{
  protected static final int ITEMID = 0;
  protected static final int ITEMNAME = 1;
  protected static final int DEFAULTPRICING = 2;
  protected static final int PRICINGLEVEL1 = 3;
  protected static final int PRICINGLEVEL2 = 4;
  protected static final int PRICINGLEVEL3 = 5;
  protected static final int PRICINGLEVEL4 = 6;
  protected static final int PRICINGLEVEL5 = 7;
  protected static final int CREATEDBY = 8;
  protected static final int LASTUPDATELOGIN = 9;
  protected static final int LASTUPDATEDBY = 10;
  protected static final int CREATIONDATE = 11;
  protected static final int LASTUPDATEDATE = 12;
  private static oracle.apps.fnd.framework.server.OAEntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public RscIfbTransactionsPricingInfoEOImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (oracle.apps.fnd.framework.server.OAEntityDefImpl)EntityDefImpl.findDefObject("oracle.apps.po.rscapps.oss.iftransactions.common.entityobjects.RscIfbTransactionsPricingInfoEO");
    }
    return mDefinitionObject;
  }

  /**
   * 
   * Add attribute defaulting logic in this method.
   */
  public void create(AttributeList attributeList)
  {
    super.create(attributeList);
  }

  /**
   * 
   * Add entity remove logic in this method.
   */
  public void remove()
  {
    super.remove();
  }

  /**
   * 
   * Add Entity validation code in this method.
   */
  protected void validateEntity()
  {
    super.validateEntity();
  }

  /**
   * 
   * Add locking logic here.
   */
  public void lock()
  {
    super.lock();
  }

  /**
   * 
   * Custom DML update/insert/delete logic here.
   */
  protected void doDML(int operation, TransactionEvent e)
  {
    super.doDML(operation, e);
  }

  /**
   * 
   * Gets the attribute value for ItemId, using the alias name ItemId
   */
  public Number getItemId()
  {
    return (Number)getAttributeInternal(ITEMID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ItemId
   */
  public void setItemId(Number value)
  {
    setAttributeInternal(ITEMID, value);
  }

  /**
   * 
   * Gets the attribute value for ItemName, using the alias name ItemName
   */
  public String getItemName()
  {
    return (String)getAttributeInternal(ITEMNAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ItemName
   */
  public void setItemName(String value)
  {
    setAttributeInternal(ITEMNAME, value);
  }

  /**
   * 
   * Gets the attribute value for DefaultPricing, using the alias name DefaultPricing
   */
  public Number getDefaultPricing()
  {
    return (Number)getAttributeInternal(DEFAULTPRICING);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DefaultPricing
   */
  public void setDefaultPricing(Number value)
  {
    setAttributeInternal(DEFAULTPRICING, value);
  }

  /**
   * 
   * Gets the attribute value for PricingLevel1, using the alias name PricingLevel1
   */
  public Number getPricingLevel1()
  {
    return (Number)getAttributeInternal(PRICINGLEVEL1);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PricingLevel1
   */
  public void setPricingLevel1(Number value)
  {
    setAttributeInternal(PRICINGLEVEL1, value);
  }

  /**
   * 
   * Gets the attribute value for PricingLevel2, using the alias name PricingLevel2
   */
  public Number getPricingLevel2()
  {
    return (Number)getAttributeInternal(PRICINGLEVEL2);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PricingLevel2
   */
  public void setPricingLevel2(Number value)
  {
    setAttributeInternal(PRICINGLEVEL2, value);
  }

  /**
   * 
   * Gets the attribute value for PricingLevel3, using the alias name PricingLevel3
   */
  public Number getPricingLevel3()
  {
    return (Number)getAttributeInternal(PRICINGLEVEL3);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PricingLevel3
   */
  public void setPricingLevel3(Number value)
  {
    setAttributeInternal(PRICINGLEVEL3, value);
  }

  /**
   * 
   * Gets the attribute value for PricingLevel4, using the alias name PricingLevel4
   */
  public Number getPricingLevel4()
  {
    return (Number)getAttributeInternal(PRICINGLEVEL4);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PricingLevel4
   */
  public void setPricingLevel4(Number value)
  {
    setAttributeInternal(PRICINGLEVEL4, value);
  }

  /**
   * 
   * Gets the attribute value for PricingLevel5, using the alias name PricingLevel5
   */
  public Number getPricingLevel5()
  {
    return (Number)getAttributeInternal(PRICINGLEVEL5);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PricingLevel5
   */
  public void setPricingLevel5(Number value)
  {
    setAttributeInternal(PRICINGLEVEL5, value);
  }

  /**
   * 
   * Gets the attribute value for CreatedBy, using the alias name CreatedBy
   */
  public Number getCreatedBy()
  {
    return (Number)getAttributeInternal(CREATEDBY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CreatedBy
   */
  public void setCreatedBy(Number value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * 
   * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
   */
  public Number getLastUpdateLogin()
  {
    return (Number)getAttributeInternal(LASTUPDATELOGIN);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LastUpdateLogin
   */
  public void setLastUpdateLogin(Number value)
  {
    setAttributeInternal(LASTUPDATELOGIN, value);
  }

  /**
   * 
   * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
   */
  public Number getLastUpdatedBy()
  {
    return (Number)getAttributeInternal(LASTUPDATEDBY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LastUpdatedBy
   */
  public void setLastUpdatedBy(Number value)
  {
    setAttributeInternal(LASTUPDATEDBY, value);
  }

  /**
   * 
   * Gets the attribute value for CreationDate, using the alias name CreationDate
   */
  public Date getCreationDate()
  {
    return (Date)getAttributeInternal(CREATIONDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CreationDate
   */
  public void setCreationDate(Date value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * 
   * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
   */
  public Date getLastUpdateDate()
  {
    return (Date)getAttributeInternal(LASTUPDATEDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LastUpdateDate
   */
  public void setLastUpdateDate(Date value)
  {
    setAttributeInternal(LASTUPDATEDATE, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ITEMID:
        return getItemId();
      case ITEMNAME:
        return getItemName();
      case DEFAULTPRICING:
        return getDefaultPricing();
      case PRICINGLEVEL1:
        return getPricingLevel1();
      case PRICINGLEVEL2:
        return getPricingLevel2();
      case PRICINGLEVEL3:
        return getPricingLevel3();
      case PRICINGLEVEL4:
        return getPricingLevel4();
      case PRICINGLEVEL5:
        return getPricingLevel5();
      case CREATEDBY:
        return getCreatedBy();
      case LASTUPDATELOGIN:
        return getLastUpdateLogin();
      case LASTUPDATEDBY:
        return getLastUpdatedBy();
      case CREATIONDATE:
        return getCreationDate();
      case LASTUPDATEDATE:
        return getLastUpdateDate();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ITEMID:
        setItemId((Number)value);
        return;
      case ITEMNAME:
        setItemName((String)value);
        return;
      case DEFAULTPRICING:
        setDefaultPricing((Number)value);
        return;
      case PRICINGLEVEL1:
        setPricingLevel1((Number)value);
        return;
      case PRICINGLEVEL2:
        setPricingLevel2((Number)value);
        return;
      case PRICINGLEVEL3:
        setPricingLevel3((Number)value);
        return;
      case PRICINGLEVEL4:
        setPricingLevel4((Number)value);
        return;
      case PRICINGLEVEL5:
        setPricingLevel5((Number)value);
        return;
      case CREATEDBY:
        setCreatedBy((Number)value);
        return;
      case LASTUPDATELOGIN:
        setLastUpdateLogin((Number)value);
        return;
      case LASTUPDATEDBY:
        setLastUpdatedBy((Number)value);
        return;
      case CREATIONDATE:
        setCreationDate((Date)value);
        return;
      case LASTUPDATEDATE:
        setLastUpdateDate((Date)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number itemId)
  {
    return new Key(new Object[] {itemId});
  }
}