package oracle.apps.po.rscapps.oss.iftransactions.common.entityobjects;
import oracle.apps.fnd.framework.server.OAEntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.AttributeList;
import oracle.jbo.server.TransactionEvent;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
import oracle.jbo.Key;
import oracle.jbo.domain.RowID;
import oracle.apps.fnd.framework.server.OADBTransaction;

//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class RscIfbTransactionsItemOutEOImpl extends OAEntityImpl 
{
  protected static final int REPLACEMENTID = 0;
  protected static final int ISRSCITEM = 1;
  protected static final int REPLACEMENTITEMMODELNAME = 2;
  protected static final int REPLACEMENTITEMSERIALNUM = 3;
  protected static final int REPLACEMENTITEMMFG = 4;
  protected static final int REPLACEMENTITEMTYPE = 5;
  protected static final int BATCHID = 6;
  protected static final int UPGRADECREDITVALUE = 7;
  protected static final int STATUS = 8;
  protected static final int ADDITIONALINFO1 = 9;
  protected static final int ADDITIONALINFO2 = 10;
  protected static final int ADDITIONALINFO3 = 11;
  protected static final int ADDITIONALINFO4 = 12;
  protected static final int ADDITIONALINFO5 = 13;
  protected static final int ADDITIONALINFO6 = 14;
  protected static final int ADDITIONALINFO7 = 15;
  protected static final int ADDITIONALINFO8 = 16;
  protected static final int ADDITIONALINFO9 = 17;
  protected static final int ADDITIONALINFO10 = 18;
  protected static final int ADDITIONALINFO11 = 19;
  protected static final int ADDITIONALINFO12 = 20;
  protected static final int ADDITIONALINFO13 = 21;
  protected static final int ADDITIONALINFO14 = 22;
  protected static final int ADDITIONALINFO15 = 23;
  protected static final int CREATEDBY = 24;
  protected static final int LASTUPDATELOGIN = 25;
  protected static final int LASTUPDATEDBY = 26;
  protected static final int CREATIONDATE = 27;
  protected static final int LASTUPDATEDATE = 28;
  protected static final int REPLACEMENTITEMSERIAL = 29;
  protected static final int ROWID = 30;









  private static oracle.apps.fnd.framework.server.OAEntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public RscIfbTransactionsItemOutEOImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (oracle.apps.fnd.framework.server.OAEntityDefImpl)EntityDefImpl.findDefObject("oracle.apps.po.rscapps.oss.iftransactions.common.entityobjects.RscIfbTransactionsItemOutEO");
    }
    return mDefinitionObject;
  }













  /**
   * 
   * Add attribute defaulting logic in this method.
   */
  public void create(AttributeList attributeList)
  {
    super.create(attributeList);

    // Default REPLACEMENT_ID value to sequence generated value
    OADBTransaction oadb = getOADBTransaction();
    Number replacementId	 = oadb.getSequenceValue("RSC_IFB_UPGRADES_ITEM_OUT_SEQ");
    setReplacementId(replacementId);
  }

  /**
   * 
   * Add entity remove logic in this method.
   */
  public void remove()
  {
    super.remove();
  }

  /**
   * 
   * Add Entity validation code in this method.
   */
  protected void validateEntity()
  {
    super.validateEntity();
  }

  /**
   * 
   * Add locking logic here.
   */
  public void lock()
  {
    super.lock();
  }

  /**
   * 
   * Custom DML update/insert/delete logic here.
   */
  protected void doDML(int operation, TransactionEvent e)
  {
    super.doDML(operation, e);
  }

  /**
   * 
   * Gets the attribute value for ReplacementId, using the alias name ReplacementId
   */
  public Number getReplacementId()
  {
    return (Number)getAttributeInternal(REPLACEMENTID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ReplacementId
   */
  public void setReplacementId(Number value)
  {
    setAttributeInternal(REPLACEMENTID, value);
  }

  /**
   * 
   * Gets the attribute value for IsRscItem, using the alias name IsRscItem
   */
  public String getIsRscItem()
  {
    return (String)getAttributeInternal(ISRSCITEM);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IsRscItem
   */
  public void setIsRscItem(String value)
  {
    setAttributeInternal(ISRSCITEM, value);
  }

  /**
   * 
   * Gets the attribute value for ReplacementItemModelName, using the alias name ReplacementItemModelName
   */
  public String getReplacementItemModelName()
  {
    return (String)getAttributeInternal(REPLACEMENTITEMMODELNAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ReplacementItemModelName
   */
  public void setReplacementItemModelName(String value)
  {
    setAttributeInternal(REPLACEMENTITEMMODELNAME, value);
  }

  /**
   * 
   * Gets the attribute value for ReplacementItemSerialNum, using the alias name ReplacementItemSerialNum
   */
  public String getReplacementItemSerialNum()
  {
    return (String)getAttributeInternal(REPLACEMENTITEMSERIALNUM);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ReplacementItemSerialNum
   */
  public void setReplacementItemSerialNum(String value)
  {
    setAttributeInternal(REPLACEMENTITEMSERIALNUM, value);
  }

  /**
   * 
   * Gets the attribute value for ReplacementItemMfg, using the alias name ReplacementItemMfg
   */
  public String getReplacementItemMfg()
  {
    return (String)getAttributeInternal(REPLACEMENTITEMMFG);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ReplacementItemMfg
   */
  public void setReplacementItemMfg(String value)
  {
    setAttributeInternal(REPLACEMENTITEMMFG, value);
  }

  /**
   * 
   * Gets the attribute value for ReplacementItemType, using the alias name ReplacementItemType
   */
  public String getReplacementItemType()
  {
    return (String)getAttributeInternal(REPLACEMENTITEMTYPE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ReplacementItemType
   */
  public void setReplacementItemType(String value)
  {
    setAttributeInternal(REPLACEMENTITEMTYPE, value);
  }

  /**
   * 
   * Gets the attribute value for BatchId, using the alias name BatchId
   */
  public Number getBatchId()
  {
    return (Number)getAttributeInternal(BATCHID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for BatchId
   */
  public void setBatchId(Number value)
  {
    setAttributeInternal(BATCHID, value);
  }

  /**
   * 
   * Gets the attribute value for UpgradeCreditValue, using the alias name UpgradeCreditValue
   */
  public Number getUpgradeCreditValue()
  {
    return (Number)getAttributeInternal(UPGRADECREDITVALUE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for UpgradeCreditValue
   */
  public void setUpgradeCreditValue(Number value)
  {
    setAttributeInternal(UPGRADECREDITVALUE, value);
  }

  /**
   * 
   * Gets the attribute value for Status, using the alias name Status
   */
  public String getStatus()
  {
    return (String)getAttributeInternal(STATUS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Status
   */
  public void setStatus(String value)
  {
    setAttributeInternal(STATUS, value);
  }

  /**
   * 
   * Gets the attribute value for AdditionalInfo1, using the alias name AdditionalInfo1
   */
  public String getAdditionalInfo1()
  {
    return (String)getAttributeInternal(ADDITIONALINFO1);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AdditionalInfo1
   */
  public void setAdditionalInfo1(String value)
  {
    setAttributeInternal(ADDITIONALINFO1, value);
  }

  /**
   * 
   * Gets the attribute value for AdditionalInfo2, using the alias name AdditionalInfo2
   */
  public String getAdditionalInfo2()
  {
    return (String)getAttributeInternal(ADDITIONALINFO2);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AdditionalInfo2
   */
  public void setAdditionalInfo2(String value)
  {
    setAttributeInternal(ADDITIONALINFO2, value);
  }

  /**
   * 
   * Gets the attribute value for AdditionalInfo3, using the alias name AdditionalInfo3
   */
  public String getAdditionalInfo3()
  {
    return (String)getAttributeInternal(ADDITIONALINFO3);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AdditionalInfo3
   */
  public void setAdditionalInfo3(String value)
  {
    setAttributeInternal(ADDITIONALINFO3, value);
  }

  /**
   * 
   * Gets the attribute value for AdditionalInfo4, using the alias name AdditionalInfo4
   */
  public String getAdditionalInfo4()
  {
    return (String)getAttributeInternal(ADDITIONALINFO4);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AdditionalInfo4
   */
  public void setAdditionalInfo4(String value)
  {
    setAttributeInternal(ADDITIONALINFO4, value);
  }

  /**
   * 
   * Gets the attribute value for AdditionalInfo5, using the alias name AdditionalInfo5
   */
  public String getAdditionalInfo5()
  {
    return (String)getAttributeInternal(ADDITIONALINFO5);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AdditionalInfo5
   */
  public void setAdditionalInfo5(String value)
  {
    setAttributeInternal(ADDITIONALINFO5, value);
  }

  /**
   * 
   * Gets the attribute value for AdditionalInfo6, using the alias name AdditionalInfo6
   */
  public String getAdditionalInfo6()
  {
    return (String)getAttributeInternal(ADDITIONALINFO6);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AdditionalInfo6
   */
  public void setAdditionalInfo6(String value)
  {
    setAttributeInternal(ADDITIONALINFO6, value);
  }

  /**
   * 
   * Gets the attribute value for AdditionalInfo7, using the alias name AdditionalInfo7
   */
  public String getAdditionalInfo7()
  {
    return (String)getAttributeInternal(ADDITIONALINFO7);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AdditionalInfo7
   */
  public void setAdditionalInfo7(String value)
  {
    setAttributeInternal(ADDITIONALINFO7, value);
  }

  /**
   * 
   * Gets the attribute value for AdditionalInfo8, using the alias name AdditionalInfo8
   */
  public String getAdditionalInfo8()
  {
    return (String)getAttributeInternal(ADDITIONALINFO8);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AdditionalInfo8
   */
  public void setAdditionalInfo8(String value)
  {
    setAttributeInternal(ADDITIONALINFO8, value);
  }

  /**
   * 
   * Gets the attribute value for AdditionalInfo9, using the alias name AdditionalInfo9
   */
  public String getAdditionalInfo9()
  {
    return (String)getAttributeInternal(ADDITIONALINFO9);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AdditionalInfo9
   */
  public void setAdditionalInfo9(String value)
  {
    setAttributeInternal(ADDITIONALINFO9, value);
  }

  /**
   * 
   * Gets the attribute value for AdditionalInfo10, using the alias name AdditionalInfo10
   */
  public String getAdditionalInfo10()
  {
    return (String)getAttributeInternal(ADDITIONALINFO10);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AdditionalInfo10
   */
  public void setAdditionalInfo10(String value)
  {
    setAttributeInternal(ADDITIONALINFO10, value);
  }

  /**
   * 
   * Gets the attribute value for AdditionalInfo11, using the alias name AdditionalInfo11
   */
  public String getAdditionalInfo11()
  {
    return (String)getAttributeInternal(ADDITIONALINFO11);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AdditionalInfo11
   */
  public void setAdditionalInfo11(String value)
  {
    setAttributeInternal(ADDITIONALINFO11, value);
  }

  /**
   * 
   * Gets the attribute value for AdditionalInfo12, using the alias name AdditionalInfo12
   */
  public String getAdditionalInfo12()
  {
    return (String)getAttributeInternal(ADDITIONALINFO12);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AdditionalInfo12
   */
  public void setAdditionalInfo12(String value)
  {
    setAttributeInternal(ADDITIONALINFO12, value);
  }

  /**
   * 
   * Gets the attribute value for AdditionalInfo13, using the alias name AdditionalInfo13
   */
  public String getAdditionalInfo13()
  {
    return (String)getAttributeInternal(ADDITIONALINFO13);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AdditionalInfo13
   */
  public void setAdditionalInfo13(String value)
  {
    setAttributeInternal(ADDITIONALINFO13, value);
  }

  /**
   * 
   * Gets the attribute value for AdditionalInfo14, using the alias name AdditionalInfo14
   */
  public String getAdditionalInfo14()
  {
    return (String)getAttributeInternal(ADDITIONALINFO14);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AdditionalInfo14
   */
  public void setAdditionalInfo14(String value)
  {
    setAttributeInternal(ADDITIONALINFO14, value);
  }

  /**
   * 
   * Gets the attribute value for AdditionalInfo15, using the alias name AdditionalInfo15
   */
  public String getAdditionalInfo15()
  {
    return (String)getAttributeInternal(ADDITIONALINFO15);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AdditionalInfo15
   */
  public void setAdditionalInfo15(String value)
  {
    setAttributeInternal(ADDITIONALINFO15, value);
  }

  /**
   * 
   * Gets the attribute value for CreatedBy, using the alias name CreatedBy
   */
  public Number getCreatedBy()
  {
    return (Number)getAttributeInternal(CREATEDBY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CreatedBy
   */
  public void setCreatedBy(Number value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * 
   * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
   */
  public Number getLastUpdateLogin()
  {
    return (Number)getAttributeInternal(LASTUPDATELOGIN);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LastUpdateLogin
   */
  public void setLastUpdateLogin(Number value)
  {
    setAttributeInternal(LASTUPDATELOGIN, value);
  }

  /**
   * 
   * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
   */
  public Number getLastUpdatedBy()
  {
    return (Number)getAttributeInternal(LASTUPDATEDBY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LastUpdatedBy
   */
  public void setLastUpdatedBy(Number value)
  {
    setAttributeInternal(LASTUPDATEDBY, value);
  }

  /**
   * 
   * Gets the attribute value for CreationDate, using the alias name CreationDate
   */
  public Date getCreationDate()
  {
    return (Date)getAttributeInternal(CREATIONDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CreationDate
   */
  public void setCreationDate(Date value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * 
   * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
   */
  public Date getLastUpdateDate()
  {
    return (Date)getAttributeInternal(LASTUPDATEDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LastUpdateDate
   */
  public void setLastUpdateDate(Date value)
  {
    setAttributeInternal(LASTUPDATEDATE, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case REPLACEMENTID:
        return getReplacementId();
      case ISRSCITEM:
        return getIsRscItem();
      case REPLACEMENTITEMMODELNAME:
        return getReplacementItemModelName();
      case REPLACEMENTITEMSERIALNUM:
        return getReplacementItemSerialNum();
      case REPLACEMENTITEMMFG:
        return getReplacementItemMfg();
      case REPLACEMENTITEMTYPE:
        return getReplacementItemType();
      case BATCHID:
        return getBatchId();
      case UPGRADECREDITVALUE:
        return getUpgradeCreditValue();
      case STATUS:
        return getStatus();
      case ADDITIONALINFO1:
        return getAdditionalInfo1();
      case ADDITIONALINFO2:
        return getAdditionalInfo2();
      case ADDITIONALINFO3:
        return getAdditionalInfo3();
      case ADDITIONALINFO4:
        return getAdditionalInfo4();
      case ADDITIONALINFO5:
        return getAdditionalInfo5();
      case ADDITIONALINFO6:
        return getAdditionalInfo6();
      case ADDITIONALINFO7:
        return getAdditionalInfo7();
      case ADDITIONALINFO8:
        return getAdditionalInfo8();
      case ADDITIONALINFO9:
        return getAdditionalInfo9();
      case ADDITIONALINFO10:
        return getAdditionalInfo10();
      case ADDITIONALINFO11:
        return getAdditionalInfo11();
      case ADDITIONALINFO12:
        return getAdditionalInfo12();
      case ADDITIONALINFO13:
        return getAdditionalInfo13();
      case ADDITIONALINFO14:
        return getAdditionalInfo14();
      case ADDITIONALINFO15:
        return getAdditionalInfo15();
      case CREATEDBY:
        return getCreatedBy();
      case LASTUPDATELOGIN:
        return getLastUpdateLogin();
      case LASTUPDATEDBY:
        return getLastUpdatedBy();
      case CREATIONDATE:
        return getCreationDate();
      case LASTUPDATEDATE:
        return getLastUpdateDate();
      case REPLACEMENTITEMSERIAL:
        return getReplacementItemSerial();
      case ROWID:
        return getRowID();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case REPLACEMENTID:
        setReplacementId((Number)value);
        return;
      case ISRSCITEM:
        setIsRscItem((String)value);
        return;
      case REPLACEMENTITEMMODELNAME:
        setReplacementItemModelName((String)value);
        return;
      case REPLACEMENTITEMSERIALNUM:
        setReplacementItemSerialNum((String)value);
        return;
      case REPLACEMENTITEMMFG:
        setReplacementItemMfg((String)value);
        return;
      case REPLACEMENTITEMTYPE:
        setReplacementItemType((String)value);
        return;
      case BATCHID:
        setBatchId((Number)value);
        return;
      case UPGRADECREDITVALUE:
        setUpgradeCreditValue((Number)value);
        return;
      case STATUS:
        setStatus((String)value);
        return;
      case ADDITIONALINFO1:
        setAdditionalInfo1((String)value);
        return;
      case ADDITIONALINFO2:
        setAdditionalInfo2((String)value);
        return;
      case ADDITIONALINFO3:
        setAdditionalInfo3((String)value);
        return;
      case ADDITIONALINFO4:
        setAdditionalInfo4((String)value);
        return;
      case ADDITIONALINFO5:
        setAdditionalInfo5((String)value);
        return;
      case ADDITIONALINFO6:
        setAdditionalInfo6((String)value);
        return;
      case ADDITIONALINFO7:
        setAdditionalInfo7((String)value);
        return;
      case ADDITIONALINFO8:
        setAdditionalInfo8((String)value);
        return;
      case ADDITIONALINFO9:
        setAdditionalInfo9((String)value);
        return;
      case ADDITIONALINFO10:
        setAdditionalInfo10((String)value);
        return;
      case ADDITIONALINFO11:
        setAdditionalInfo11((String)value);
        return;
      case ADDITIONALINFO12:
        setAdditionalInfo12((String)value);
        return;
      case ADDITIONALINFO13:
        setAdditionalInfo13((String)value);
        return;
      case ADDITIONALINFO14:
        setAdditionalInfo14((String)value);
        return;
      case ADDITIONALINFO15:
        setAdditionalInfo15((String)value);
        return;
      case CREATEDBY:
        setCreatedBy((Number)value);
        return;
      case LASTUPDATELOGIN:
        setLastUpdateLogin((Number)value);
        return;
      case LASTUPDATEDBY:
        setLastUpdatedBy((Number)value);
        return;
      case CREATIONDATE:
        setCreationDate((Date)value);
        return;
      case LASTUPDATEDATE:
        setLastUpdateDate((Date)value);
        return;
      case REPLACEMENTITEMSERIAL:
        setReplacementItemSerial((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }



  /**
   * 
   * Gets the attribute value for ReplacementItemSerial, using the alias name ReplacementItemSerial
   */
  public String getReplacementItemSerial()
  {
    return (String)getAttributeInternal(REPLACEMENTITEMSERIAL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ReplacementItemSerial
   */
  public void setReplacementItemSerial(String value)
  {
    setAttributeInternal(REPLACEMENTITEMSERIAL, value);
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number replacementId)
  {
    return new Key(new Object[] {replacementId});
  }

  /**
   * 
   * Gets the attribute value for RowID, using the alias name RowID
   */
  public RowID getRowID()
  {
    return (RowID)getAttributeInternal(ROWID);
  }



}