package oracle.apps.po.rscapps.oss.iftransactions.admin.viewobjects;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;
import oracle.apps.fnd.framework.server.OADBTransactionImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class ApproverViewBatchesSummaryReadOnlyViewVOImpl extends OAViewObjectImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public ApproverViewBatchesSummaryReadOnlyViewVOImpl()
  {
  }

  /**
   * Init Query
   */
  public void initQuery() 
  {
    OADBTransactionImpl oadb = (OADBTransactionImpl) getDBTransaction();
    String userId = ""+ oadb.getUserId();
    String userName = oadb.getUserName();

    setWhereClauseParam(0, userName);    
    executeQuery();
  } 
}