package oracle.apps.po.rscapps.oss.iftransactions.admin.viewobjects;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class NewRscIfbTransactionsDealrDistDefnVOImpl extends OAViewObjectImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public NewRscIfbTransactionsDealrDistDefnVOImpl()
  {
  }

  /**
   * Init Query
   */
  public void initQuery() 
  {
    executeQuery();
  }
}