package oracle.apps.po.rscapps.oss.iftransactions.influencer.viewobjects;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class TransientYesNoAndDropdownsVOImpl extends OAViewObjectImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public TransientYesNoAndDropdownsVOImpl()
  {
  }
}