package oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects.nonentityobjects;
import oracle.apps.fnd.framework.server.OAViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class BatteryPlanVORowImpl extends OAViewRowImpl 
{





  protected static final int BATTERYPLAN = 0;
  protected static final int BATTERYPLANVALUE = 1;
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public BatteryPlanVORowImpl()
  {
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Batteryplan
   */
  public String getBatteryplan()
  {
    return (String)getAttributeInternal(BATTERYPLAN);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Batteryplan
   */
  public void setBatteryplan(String value)
  {
    setAttributeInternal(BATTERYPLAN, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case BATTERYPLAN:
        return getBatteryplan();
      case BATTERYPLANVALUE:
        return getBatteryplanvalue();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case BATTERYPLAN:
        setBatteryplan((String)value);
        return;
      case BATTERYPLANVALUE:
        setBatteryplanvalue((Number)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Batteryplanvalue
   */
  public Number getBatteryplanvalue()
  {
    return (Number)getAttributeInternal(BATTERYPLANVALUE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Batteryplanvalue
   */
  public void setBatteryplanvalue(Number value)
  {
    setAttributeInternal(BATTERYPLANVALUE, value);
  }
}