package oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects.nonentityobjects;
import oracle.apps.fnd.framework.server.OAViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class PetinfoSpayNeuterVORowImpl extends OAViewRowImpl 
{





  protected static final int SPAYNEUTER = 0;
  protected static final int SPAYNEUTERVALUE = 1;
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public PetinfoSpayNeuterVORowImpl()
  {
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Spayneuter
   */
  public String getSpayneuter()
  {
    return (String)getAttributeInternal(SPAYNEUTER);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Spayneuter
   */
  public void setSpayneuter(String value)
  {
    setAttributeInternal(SPAYNEUTER, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case SPAYNEUTER:
        return getSpayneuter();
      case SPAYNEUTERVALUE:
        return getSpayneutervalue();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case SPAYNEUTER:
        setSpayneuter((String)value);
        return;
      case SPAYNEUTERVALUE:
        setSpayneutervalue((Number)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Spayneutervalue
   */
  public Number getSpayneutervalue()
  {
    return (Number)getAttributeInternal(SPAYNEUTERVALUE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Spayneutervalue
   */
  public void setSpayneutervalue(Number value)
  {
    setAttributeInternal(SPAYNEUTERVALUE, value);
  }
}