package oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects.nonentityobjects;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class PetinfoSpayNeuterVOImpl extends OAViewObjectImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public PetinfoSpayNeuterVOImpl()
  {
  }

  /**
   * Init Query
   */
  public void initQuery() 
  {
    executeQuery();
  }    
}