package oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects.nonentityobjects;
import oracle.apps.fnd.framework.server.OAViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VetReqToBeIncludedVORowImpl extends OAViewRowImpl 
{



  protected static final int VETREQTOBEINCLUDED = 0;
  protected static final int VETREQTOBEINCLUDEDVALUE = 1;
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VetReqToBeIncludedVORowImpl()
  {
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Vetreqtobeincluded
   */
  public String getVetreqtobeincluded()
  {
    return (String)getAttributeInternal(VETREQTOBEINCLUDED);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Vetreqtobeincluded
   */
  public void setVetreqtobeincluded(String value)
  {
    setAttributeInternal(VETREQTOBEINCLUDED, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case VETREQTOBEINCLUDED:
        return getVetreqtobeincluded();
      case VETREQTOBEINCLUDEDVALUE:
        return getVetreqtobeincludedvalue();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case VETREQTOBEINCLUDED:
        setVetreqtobeincluded((String)value);
        return;
      case VETREQTOBEINCLUDEDVALUE:
        setVetreqtobeincludedvalue((Number)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Vetreqtobeincludedvalue
   */
  public Number getVetreqtobeincludedvalue()
  {
    return (Number)getAttributeInternal(VETREQTOBEINCLUDEDVALUE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Vetreqtobeincludedvalue
   */
  public void setVetreqtobeincludedvalue(Number value)
  {
    setAttributeInternal(VETREQTOBEINCLUDEDVALUE, value);
  }
}