package oracle.apps.po.rscapps.oss.iftransactions.moneyback.applicationmodules;
import com.sun.java.util.collections.ArrayList;

import oracle.apps.fnd.common.MessageToken;
import oracle.apps.fnd.framework.OAException;
import oracle.apps.po.rscapps.oss.iftransactions.common.applicationmodules.BatchCreationAMImpl;
import oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects.CheckForDuplicateSerialNumberVOImpl;
import oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects.CurrentBatchVOImpl;
import oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects.GetCreditForThisUserVOImpl;
import oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects.GetProductNameFromProductIdVOImpl;
import oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects.LPTypeDropDownVOImpl;
import oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects.NewBatchVOImpl;
import oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects.NewNonRscItemsInVOImpl;
import oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects.NewRscItemsInVOImpl;
import oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects.NewRscItemsOutVOImpl;
import oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects.PetinfoBreedDropdownVOImpl;
import oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects.PetinfoSexDropdownVOImpl;
import oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects.nonentityobjects.BatteryPlanVOImpl;
import oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects.nonentityobjects.CreateBatchTypeVOImpl;
import oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects.nonentityobjects.LPUsedVOImpl;
import oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects.nonentityobjects.PetinfoSpayNeuterVOImpl;

import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class MoneyBackBatchCreationAMImpl extends BatchCreationAMImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public MoneyBackBatchCreationAMImpl()
  {
  }

  /**
   * 
   * Container's getter for BatchCreationAM1
   */
  public ApplicationModuleImpl getBatchCreationAM1()
  {
    return (ApplicationModuleImpl)findApplicationModule("BatchCreationAM1");
  }

  /**
   * Checks whether all the mandatory fields have been entered.
   * Doing this programmatically instead of using the UIX "IsRequired" flag - as the UIX route 
   * will prevent any PPR from happening on the page (Eg: add rows to table) unless data exists in the mandatory fields.
   * What can I say ... Life is @#$@#$@ good !!!
   */
  public String isBatchEligibleForBatchSaveOperation() 
  {
    String returnValue = "NO";
    /* *******************************************************
       Mandatory Fields For Batch Has Been Defined As Follows:
                Name
                Phone
                Email

                PurchaseDate // Added on 09/20 ... 
                BatchType    // Added on 09/26 ... This field is mapped to AdditionalInfo1

                Old Equipment
                  Serial #

                Other Brand Traded-In
                  Manufacturer
	
                New Equipment
                  Serial

                Dealer Signature
                  
    ********************************************************* */
    NewBatchVOImpl batchObj = getNewBatchVO1();

    ArrayList listOfExceptionToDisplay = new ArrayList();
    
    if(batchObj!=null) 
    {
      Row currentRowObj = batchObj.getCurrentRow();
      if(currentRowObj!=null) 
      {        
        String nameFieldValue = "" + currentRowObj.getAttribute("CustInfoName");
        String phoneFieldValue = "" + currentRowObj.getAttribute("CustInfoPhone");
        String emailFieldValue = "" + currentRowObj.getAttribute("CustInfoEmail");
        String dealerSignatureFieldValue = "" + currentRowObj.getAttribute("DealerSignature");

        if( nameFieldValue==null || nameFieldValue.equalsIgnoreCase("null") || nameFieldValue.length()==0 ) 
        {
          MessageToken[] messageTokensArray = { new MessageToken("MISSING_FIELD_INFO", "\"Name\"") } ;
          listOfExceptionToDisplay.add(new OAException("PO", "RSC_OSS_IFB_BATCH_MISSING_INFO", messageTokensArray, OAException.ERROR, null) );
        }

        if( phoneFieldValue==null || phoneFieldValue.equalsIgnoreCase("null") || phoneFieldValue.length()==0 ) 
        {
          MessageToken[] messageTokensArray = { new MessageToken("MISSING_FIELD_INFO", "\"Phone\"") } ;
          listOfExceptionToDisplay.add(new OAException("PO", "RSC_OSS_IFB_BATCH_MISSING_INFO", messageTokensArray, OAException.ERROR, null) );
        }

        if( emailFieldValue==null || emailFieldValue.equalsIgnoreCase("null") || emailFieldValue.length()==0 ) 
        {
          MessageToken[] messageTokensArray = { new MessageToken("MISSING_FIELD_INFO", "\"Email\"") } ;
          listOfExceptionToDisplay.add(new OAException("PO", "RSC_OSS_IFB_BATCH_MISSING_INFO", messageTokensArray, OAException.ERROR, null) );
        }      

        if( dealerSignatureFieldValue==null || dealerSignatureFieldValue.equalsIgnoreCase("null") || dealerSignatureFieldValue.length()==0 ) 
        {
          MessageToken[] messageTokensArray = { new MessageToken("MISSING_FIELD_INFO", "\"Dealer Signature\"") } ;
          listOfExceptionToDisplay.add(new OAException("PO", "RSC_OSS_IFB_BATCH_MISSING_INFO", messageTokensArray, OAException.ERROR, null) );          
        }
      }
    }

    if(listOfExceptionToDisplay.isEmpty()) 
    {
      returnValue = "YES";
    }
    else 
    {
      OAException.raiseBundledOAException(listOfExceptionToDisplay);
    }

    return returnValue;    
  }

  /**
   * 
   * Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args)
  {
    launchTester("oracle.apps.po.rscapps.oss.iftransactions.moneyback.applicationmodules", "MoneyBackBatchCreationAMLocal");
  }

  /**
   * 
   * Container's getter for LPTypeDropDownVO1
   */
  public LPTypeDropDownVOImpl getLPTypeDropDownVO1()
  {
    return (LPTypeDropDownVOImpl)findViewObject("LPTypeDropDownVO1");
  }

  /**
   * 
   * Container's getter for CreateBatchTypeVO1
   */
  public CreateBatchTypeVOImpl getCreateBatchTypeVO1()
  {
    return (CreateBatchTypeVOImpl)findViewObject("CreateBatchTypeVO1");
  }

  /**
   * 
   * Container's getter for GetCreditForThisUserVO1
   */
  public GetCreditForThisUserVOImpl getGetCreditForThisUserVO1()
  {
    return (GetCreditForThisUserVOImpl)findViewObject("GetCreditForThisUserVO1");
  }

  /**
   * 
   * Container's getter for BatteryPlanVO1
   */
  public BatteryPlanVOImpl getBatteryPlanVO1()
  {
    return (BatteryPlanVOImpl)findViewObject("BatteryPlanVO1");
  }

  /**
   * 
   * Container's getter for NewRscItemsInVO1
   */
  public NewRscItemsInVOImpl getNewRscItemsInVO1()
  {
    return (NewRscItemsInVOImpl)findViewObject("NewRscItemsInVO1");
  }

  /**
   * 
   * Container's getter for PetinfoSpayNeuterVO1
   */
  public PetinfoSpayNeuterVOImpl getPetinfoSpayNeuterVO1()
  {
    return (PetinfoSpayNeuterVOImpl)findViewObject("PetinfoSpayNeuterVO1");
  }

  /**
   * 
   * Container's getter for CurrentBatchVO1
   */
  public CurrentBatchVOImpl getCurrentBatchVO1()
  {
    return (CurrentBatchVOImpl)findViewObject("CurrentBatchVO1");
  }

  /**
   * 
   * Container's getter for NewNonRscItemsInVO1
   */
  public NewNonRscItemsInVOImpl getNewNonRscItemsInVO1()
  {
    return (NewNonRscItemsInVOImpl)findViewObject("NewNonRscItemsInVO1");
  }

  /**
   * 
   * Container's getter for LPUsedVO1
   */
  public LPUsedVOImpl getLPUsedVO1()
  {
    return (LPUsedVOImpl)findViewObject("LPUsedVO1");
  }

  /**
   * 
   * Container's getter for NewBatchVO1
   */
  public NewBatchVOImpl getNewBatchVO1()
  {
    return (NewBatchVOImpl)findViewObject("NewBatchVO1");
  }

  /**
   * 
   * Container's getter for GetProductNameFromProductIdVO1
   */
  public GetProductNameFromProductIdVOImpl getGetProductNameFromProductIdVO1()
  {
    return (GetProductNameFromProductIdVOImpl)findViewObject("GetProductNameFromProductIdVO1");
  }

  /**
   * 
   * Container's getter for CheckForDuplicateSerialNumberVO1
   */
  public CheckForDuplicateSerialNumberVOImpl getCheckForDuplicateSerialNumberVO1()
  {
    return (CheckForDuplicateSerialNumberVOImpl)findViewObject("CheckForDuplicateSerialNumberVO1");
  }

  /**
   * 
   * Container's getter for NewRscItemsOutVO1
   */
  public NewRscItemsOutVOImpl getNewRscItemsOutVO1()
  {
    return (NewRscItemsOutVOImpl)findViewObject("NewRscItemsOutVO1");
  }

  /**
   * 
   * Container's getter for PetinfoBreedDropdownVO1
   */
  public PetinfoBreedDropdownVOImpl getPetinfoBreedDropdownVO1()
  {
    return (PetinfoBreedDropdownVOImpl)findViewObject("PetinfoBreedDropdownVO1");
  }

  /**
   * 
   * Container's getter for PetinfoSexDropdownVO1
   */
  public PetinfoSexDropdownVOImpl getPetinfoSexDropdownVO1()
  {
    return (PetinfoSexDropdownVOImpl)findViewObject("PetinfoSexDropdownVO1");
  }
}