package oracle.apps.po.rscapps.oss.iftransactions.common.applicationmodules;
import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
import oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects.nonentityobjects.CustomerLovVOImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class CustomerLovAMImpl extends OAApplicationModuleImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public CustomerLovAMImpl()
  {
  }


  /**
   * 
   * Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args)
  {
    launchTester("oracle.apps.po.rscapps.oss.iftransactions.common.applicationmodules", "CustomerLovAMLocal");
  }

  /**
   * 
   * Container's getter for CustomerLovVO1
   */
  public CustomerLovVOImpl getCustomerLovVO1()
  {
    return (CustomerLovVOImpl)findViewObject("CustomerLovVO1");
  }
}