package oracle.apps.po.rscapps.oss.iftransactions.common.applicationmodules;
import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
import oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects.ItemLovVOImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class ItemLovAMImpl extends OAApplicationModuleImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public ItemLovAMImpl()
  {
  }

  /**
   * 
   * Container's getter for ItemLovVO1
   */
  public ItemLovVOImpl getItemLovVO1()
  {
    return (ItemLovVOImpl)findViewObject("ItemLovVO1");
  }

  /**
   * 
   * Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args)
  {
    launchTester("oracle.apps.po.rscapps.oss.iftransactions.common.applicationmodules", "ItemLovAMLocal");
  }
}