package oracle.apps.po.rscapps.oss.iftransactions.common.applicationmodules;
import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class PricingLevelsLovAMImpl extends OAApplicationModuleImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public PricingLevelsLovAMImpl()
  {
  }

  /**
   * 
   * Container's getter for AvailablePricingLevelsVO1
   */
  public oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects.nonentityobjects.AvailablePricingLevelsVOImpl getAvailablePricingLevelsVO1()
  {
    return (oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects.nonentityobjects.AvailablePricingLevelsVOImpl)findViewObject("AvailablePricingLevelsVO1");
  }

  /**
   * 
   * Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args)
  {
    launchTester("oracle.apps.po.rscapps.oss.iftransactions.common.applicationmodules", "PricingLevelsLovAMLocal");
  }
}