package oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;
import oracle.apps.fnd.framework.server.OADBTransactionImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class DealerViewBatchSummaryVOImpl extends OAViewObjectImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public DealerViewBatchSummaryVOImpl()
  {
  }

  /**
   * Execute Query
   */
  public void initQuery() 
  {
    OADBTransactionImpl oadb = (OADBTransactionImpl)getDBTransaction();
    String loggedInUserName = oadb.getUserName();
    int loggedInUserId = oadb.getUserId();

    setWhereClause("CREATED_BY = :1");    
    setWhereClauseParam(0, ""+loggedInUserId);    
    executeQuery();    
  }
}