package oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class GetApproverInfoForThisBatchVOImpl extends OAViewObjectImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public GetApproverInfoForThisBatchVOImpl()
  {
  }

  /**
   * Init Query
   */
  public void initQuery(String batchIdInput) 
  {
    setWhereClauseParam(0, batchIdInput);
    setWhereClauseParam(1, batchIdInput);
    setWhereClauseParam(2, batchIdInput);
    setWhereClauseParam(3, batchIdInput);    
    
    executeQuery();
  }
}