package oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class GetCreditForThisUserVOImpl extends OAViewObjectImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public GetCreditForThisUserVOImpl()
  {
  }

  /**
   * Execute Query
   */
  public void initQuery(String userNameInput, String itemNameInput) 
  {
    setWhereClauseParam(0, userNameInput);
    setWhereClauseParam(1, itemNameInput);
    executeQuery();
  }
}