package oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class GetDropDownForTableIdandItemIdVOImpl extends OAViewObjectImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public GetDropDownForTableIdandItemIdVOImpl()
  {
  }

  /**
   * Init Query
   */
  public void initQuery(String itemId, String tableId) 
  {
    setWhereClauseParam(0, itemId);
    setWhereClauseParam(1, tableId);    
    executeQuery();
  }         
}