package oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class GetProductNameFromProductIdVOImpl extends OAViewObjectImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public GetProductNameFromProductIdVOImpl()
  {
  }

  /**
   * Init Query
   */
  public void initQuery() 
  {
    initQuery("-1");
  }

  /**
   * Init Query with Product Id
   */
  public void initQuery(String productIdInput) 
  {
    String productIdToBind = "-1";
    
    setWhereClause(null);
    setWhereClauseParams(null);

    setWhereClause("UPPER(ITEM_CODE) = UPPER(:1)");    
    if(productIdInput!=null && productIdInput.length()>0 && !productIdInput.equalsIgnoreCase("null")) 
    {
      productIdToBind = productIdInput;
    }

    setWhereClauseParam(0, productIdToBind);  
    executeQuery();
  }
}