package oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;
import oracle.apps.fnd.framework.server.OADBTransactionImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class IsThisUserADealerVOImpl extends OAViewObjectImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public IsThisUserADealerVOImpl()
  {
  }

  /**
   * Init Query
   */
  public void initQuery() 
  {
    OADBTransactionImpl oadb = (OADBTransactionImpl)getDBTransaction();
    String loggedInUserName = oadb.getUserName();
    int loggedInUserId = oadb.getUserId();
    
    setWhereClauseParam(0, ""+loggedInUserName);
    executeQuery();    
  }  
}