package oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects;
import oracle.apps.fnd.framework.server.OAViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class LPTypeDropDownVORowImpl extends OAViewRowImpl 
{
  protected static final int ITEMID = 0;


  protected static final int ITEMVALUE = 1;
  protected static final int TABLEID = 2;
  protected static final int ROWID1 = 3;
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public LPTypeDropDownVORowImpl()
  {
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute ItemId
   */
  public Number getItemId()
  {
    return (Number)getAttributeInternal(ITEMID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute ItemId
   */
  public void setItemId(Number value)
  {
    setAttributeInternal(ITEMID, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute ItemValue
   */
  public String getItemValue()
  {
    return (String)getAttributeInternal(ITEMVALUE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute ItemValue
   */
  public void setItemValue(String value)
  {
    setAttributeInternal(ITEMVALUE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute TableId
   */
  public Number getTableId()
  {
    return (Number)getAttributeInternal(TABLEID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute TableId
   */
  public void setTableId(Number value)
  {
    setAttributeInternal(TABLEID, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Rowid1
   */
  public RowID getRowid1()
  {
    return (RowID)getAttributeInternal(ROWID1);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Rowid1
   */
  public void setRowid1(RowID value)
  {
    setAttributeInternal(ROWID1, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ITEMID:
        return getItemId();
      case ITEMVALUE:
        return getItemValue();
      case TABLEID:
        return getTableId();
      case ROWID1:
        return getRowid1();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ITEMID:
        setItemId((Number)value);
        return;
      case ITEMVALUE:
        setItemValue((String)value);
        return;
      case TABLEID:
        setTableId((Number)value);
        return;
      case ROWID1:
        setRowid1((RowID)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }
}