package oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class RscItemsInVOImpl extends OAViewObjectImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public RscItemsInVOImpl()
  {
  }

  /**
   * Init Query
   */
  public void initQuery(String batchId) 
  {
    setWhereClauseParam(0, batchId);
    executeQuery();
  }   
}