package oracle.apps.po.rscapps.oss.iftransactions.admin.applicationmodules;
import java.util.HashMap;

import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
import oracle.apps.po.rscapps.oss.iftransactions.admin.viewobjects.ApproverViewBatchesPendingApprovalSummaryVOImpl;
import oracle.apps.po.rscapps.oss.iftransactions.admin.viewobjects.ApproverViewBatchesSummaryReadOnlyViewVOImpl;
import oracle.apps.po.rscapps.oss.iftransactions.admin.viewobjects.NewRscIfbTransactionsApprvDefnVOImpl;
import oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects.CurrentBatchVOImpl;
import oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects.GetApproverInfoForThisBatchVOImpl;
import oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects.NewRscItemsOutVOImpl;
import oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects.NextApproverForThisBatchImpl;
import oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects.NonRscItemsInVOImpl;
import oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects.RscItemsInVOImpl;
import oracle.apps.po.rscapps.oss.iftransactions.common.viewobjects.RscItemsOutVOImpl;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class BatchApprovalAMImpl extends OAApplicationModuleImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public BatchApprovalAMImpl()
  {
  }

  /**
   * 
   */
  public void initApproverBatchSummaryReadOnlyViewPG() 
  {
    ApproverViewBatchesSummaryReadOnlyViewVOImpl batchesSummaryReadOnlyViewObj = getApproverViewBatchesSummaryReadOnlyViewVO1();
    batchesSummaryReadOnlyViewObj.initQuery();
  }  

  /**
   * 
   */
  public void initApproveBatchSummaryPG() 
  {
    ApproverViewBatchesPendingApprovalSummaryVOImpl batchesPendingApprovalObj = getApproverViewBatchesPendingApprovalSummaryVO1();
    batchesPendingApprovalObj.initQuery();
  }

  /**
   * 
   */
  public void initApproveThisBatchPG(String batchIdInput) 
  {
    CurrentBatchVOImpl viewBatchObj = getCurrentBatchVO1();
    RscItemsOutVOImpl viewItemsOutObj = getRscItemsOutVO1();
    RscItemsInVOImpl viewRscItemsInObj = getRscItemsInVO1();
    NonRscItemsInVOImpl viewNonRscItemsInObj = getNonRscItemsInVO1();
    GetApproverInfoForThisBatchVOImpl approversInfoObj = getGetApproverInfoForThisBatchVO1();

    viewBatchObj.initQuery(batchIdInput);
    viewItemsOutObj.initQuery(batchIdInput);
    viewRscItemsInObj.initQuery(batchIdInput);
    viewNonRscItemsInObj.initQuery(batchIdInput);
    approversInfoObj.initQuery(batchIdInput);

  }

  /**
   * 
   */
  public void approveThisBatch() 
  {
    GetApproverInfoForThisBatchVOImpl approversInfoObj = getGetApproverInfoForThisBatchVO1();
    
    String nextApproverId = "";
    String nextApproverName = "" ;
    String currentApproverId = "" ;
    String currentApproverName = "" ;
    
    if(approversInfoObj!=null) 
    {
      Row currentRowObj = approversInfoObj.getRowAtRangeIndex(0);
      if(currentRowObj!=null) 
      {
        nextApproverId = "" + currentRowObj.getAttribute("NextApprvPartyId");
        nextApproverName = "" + currentRowObj.getAttribute("NextApprvPartyName");        
        currentApproverId = "" + currentRowObj.getAttribute("CurrentApprvId");     
        currentApproverName = "" + currentRowObj.getAttribute("CurrentApprvName");             
      }
    }
    
    CurrentBatchVOImpl thisBatchObj = getCurrentBatchVO1();
    if(thisBatchObj!=null) 
    {
      Row currentRowObj = thisBatchObj.getRowAtRangeIndex(0);
      if(currentRowObj!=null) 
      {
        if( nextApproverId.equalsIgnoreCase("1")) 
        {
          currentRowObj.setAttribute("ApprovalNeededFrom", new Number(1) );
          currentRowObj.setAttribute("Status", "PENDING_RSC_APPROVAL");
        } 
        else  
        {
          currentRowObj.setAttribute("ApprovalNeededFrom", new Number(Integer.parseInt(nextApproverId)));
          currentRowObj.setAttribute("Status", "PENDING_APPROVAL");
        }
      }
    }
    
    saveChanges();
  }

  /**
   * 
   */
  public void rejectThisBatch() 
  {    
    CurrentBatchVOImpl thisBatchObj = getCurrentBatchVO1();
    if(thisBatchObj!=null) 
    {
      Row currentRowObj = thisBatchObj.getRowAtRangeIndex(0);
      if(currentRowObj!=null) 
      {
        currentRowObj.setAttribute("Status", "REJECTED");
        currentRowObj.setAttribute("ApprovalNeededFrom", new Number(0));         
      }
    }

    saveChanges();
  }

  /**
   * 
   */
  public void saveChanges() 
  {
    getOADBTransaction().commit();
  }

  /**
   * 
   */
  public void approveBatches() 
  {
    ApproverViewBatchesPendingApprovalSummaryVOImpl batchesPendingApprovalObj =  getApproverViewBatchesPendingApprovalSummaryVO1();
    Row[] allTableRows = batchesPendingApprovalObj.getAllRowsInRange();
    if(allTableRows.length >0) 
    {
      for(int i=0 ; i<allTableRows.length ; i++) 
      {
        Row currRow = allTableRows[i];
        if(currRow!=null) 
        {
          String isRowSelected = "" + currRow.getAttribute("Transient1");
          if(isRowSelected.equalsIgnoreCase("Y")) 
          {
            String nextApproverId = "" + currRow.getAttribute("NextApproverId"); 
            if(nextApproverId!=null && !nextApproverId.equalsIgnoreCase("null") && nextApproverId.length() >0 ) 
            {
              if( nextApproverId.equalsIgnoreCase("1")) 
              {
                currRow.setAttribute("ApprovalNeededFrom", new Number(1) );
                currRow.setAttribute("Status", "PENDING_RSC_APPROVAL");                  
              }
              else  
              {
                currRow.setAttribute("ApprovalNeededFrom", new Number(Integer.parseInt(nextApproverId))); 
                currRow.setAttribute("Status", "PENDING_APPROVAL");
              }
            }           
          }
        }
      }
    }
    
    saveChanges();
  }

  /**
   * 
   */
  public void rejectBatches() 
  {
    ApproverViewBatchesPendingApprovalSummaryVOImpl batchesPendingApprovalObj =  getApproverViewBatchesPendingApprovalSummaryVO1();
    Row[] allTableRows = batchesPendingApprovalObj.getAllRowsInRange();
    if(allTableRows.length >0) 
    {
      for(int i=0 ; i<allTableRows.length ; i++) 
      {
        Row currRow = allTableRows[i];
        if(currRow!=null) 
        {
          String isRowSelected = "" + currRow.getAttribute("Transient1");
          if(isRowSelected.equalsIgnoreCase("Y")) 
          {
             currRow.setAttribute("Status", "REJECTED");
             currRow.setAttribute("ApprovalNeededFrom", new Number(0));              
          }
        }
      }
    }
    
    saveChanges();
  }

  /**
   * 
   */
  public HashMap getApproverInformationForThisBatch(String batchId) 
  {
    HashMap returnValue = new HashMap();
    
    GetApproverInfoForThisBatchVOImpl approversInfoObj = getGetApproverInfoForThisBatchVO1();
    approversInfoObj.initQuery(batchId);
    
    String nextApproverId = "";
    String nextApproverName = "" ;
    String currentApproverId = "" ;
    String currentApproverName = "" ;
    
    if(approversInfoObj!=null) 
    {
      Row currentRowObj = approversInfoObj.getRowAtRangeIndex(0);
      if(currentRowObj!=null) 
      {
        nextApproverId = "" + currentRowObj.getAttribute("NextApprvPartyId");
        nextApproverName = "" + currentRowObj.getAttribute("NextApprvPartyName");
        currentApproverId = "" + currentRowObj.getAttribute("CurrentApprvId");
        currentApproverName = "" + currentRowObj.getAttribute("CurrentApprvName");
        
        returnValue.put("nextApproverId", nextApproverId);
        returnValue.put("nextApproverName", nextApproverName);
        returnValue.put("currentApproverId", currentApproverId);
        returnValue.put("currentApproverName", currentApproverName);        
      }
    }

    return returnValue;
  }

  /**
   * 
   * Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args)
  {
    launchTester("oracle.apps.po.rscapps.oss.ifupgrades.server", "BatchApprovalAMLocal");
  }

  /**
   * 
   * Container's getter for GetApproverInfoForThisBatchVO1
   */
  public GetApproverInfoForThisBatchVOImpl getGetApproverInfoForThisBatchVO1()
  {
    return (GetApproverInfoForThisBatchVOImpl)findViewObject("GetApproverInfoForThisBatchVO1");
  }

  /**
   * 
   * Container's getter for NextApproverForThisBatch1
   */
  public NextApproverForThisBatchImpl getNextApproverForThisBatch1()
  {
    return (NextApproverForThisBatchImpl)findViewObject("NextApproverForThisBatch1");
  }





  /**
   * 
   * Container's getter for ApproverViewBatchesSummaryReadOnlyViewVO1
   */
  public ApproverViewBatchesSummaryReadOnlyViewVOImpl getApproverViewBatchesSummaryReadOnlyViewVO1()
  {
    return (ApproverViewBatchesSummaryReadOnlyViewVOImpl)findViewObject("ApproverViewBatchesSummaryReadOnlyViewVO1");
  }

  /**
   * 
   * Container's getter for ApproverViewBatchesPendingApprovalSummaryVO1
   */
  public ApproverViewBatchesPendingApprovalSummaryVOImpl getApproverViewBatchesPendingApprovalSummaryVO1()
  {
    return (ApproverViewBatchesPendingApprovalSummaryVOImpl)findViewObject("ApproverViewBatchesPendingApprovalSummaryVO1");
  }





  /**
   * 
   * Container's getter for NewRscIfbTransactionsApprvDefnVO1
   */
  public NewRscIfbTransactionsApprvDefnVOImpl getNewRscIfbTransactionsApprvDefnVO1()
  {
    return (NewRscIfbTransactionsApprvDefnVOImpl)findViewObject("NewRscIfbTransactionsApprvDefnVO1");
  }

  /**
   * 
   * Container's getter for NewRscItemsOutVO1
   */
  public NewRscItemsOutVOImpl getNewRscItemsOutVO1()
  {
    return (NewRscItemsOutVOImpl)findViewObject("NewRscItemsOutVO1");
  }

  /**
   * 
   * Container's getter for NonRscItemsInVO1
   */
  public NonRscItemsInVOImpl getNonRscItemsInVO1()
  {
    return (NonRscItemsInVOImpl)findViewObject("NonRscItemsInVO1");
  }

  /**
   * 
   * Container's getter for RscItemsInVO1
   */
  public RscItemsInVOImpl getRscItemsInVO1()
  {
    return (RscItemsInVOImpl)findViewObject("RscItemsInVO1");
  }

  /**
   * 
   * Container's getter for RscItemsOutVO1
   */
  public RscItemsOutVOImpl getRscItemsOutVO1()
  {
    return (RscItemsOutVOImpl)findViewObject("RscItemsOutVO1");
  }

  /**
   * 
   * Container's getter for CurrentBatchVO1
   */
  public CurrentBatchVOImpl getCurrentBatchVO1()
  {
    return (CurrentBatchVOImpl)findViewObject("CurrentBatchVO1");
  }


}